"use client";

import { useDraggable } from "@dnd-kit/core";
import { CSS } from "@dnd-kit/utilities";
import { Sparkles, Check, X, Link2, CalendarClock, GripVertical, MessageSquare } from "lucide-react";
import { cn } from "@/lib/utils";
import type { Task } from "@/lib/types";
import {
  PRIORITY_ACCENT,
  checklistProgress,
  dueLabel,
  initials,
} from "./_helpers";

interface TaskCardProps {
  task: Task;
  onOpen: (task: Task) => void;
  onAccept?: (task: Task) => void;
  onDismiss?: (task: Task) => void;
  compact?: boolean;
}

export function TaskCard({ task, onOpen, onAccept, onDismiss, compact }: TaskCardProps) {
  const { attributes, listeners, setNodeRef, transform, isDragging } = useDraggable({
    id: task.id,
    data: { type: "task", status: task.status },
  });

  const style: React.CSSProperties = {
    transform: CSS.Translate.toString(transform),
    opacity: isDragging ? 0.4 : 1,
    zIndex: isDragging ? 50 : 1,
  };

  const prog = checklistProgress(task);
  const due = dueLabel(task.dueDate);

  return (
    <div
      ref={setNodeRef}
      style={style}
      className={cn(
        "group relative flex rounded-[6px] border border-border bg-card transition-colors hover:border-foreground/40",
        isDragging && "cursor-grabbing",
      )}
    >
      {/* Priority accent strip */}
      <div className={cn("w-[3px] shrink-0 rounded-l-[6px]", PRIORITY_ACCENT[task.priority])} />

      <div className="flex min-w-0 flex-1 flex-col">
        {/* Top row: drag handle + title + Rean mark */}
        <div className="flex items-start gap-1.5 px-2.5 pt-2.5">
          <button
            {...attributes}
            {...listeners}
            className="mt-0.5 hidden shrink-0 cursor-grab text-muted-foreground/40 hover:text-foreground group-hover:block focus:outline-none active:cursor-grabbing"
            aria-label="Drag task"
            tabIndex={-1}
          >
            <GripVertical className="h-3.5 w-3.5" />
          </button>

          <button
            onClick={() => onOpen(task)}
            className="min-w-0 flex-1 text-left focus:outline-none"
          >
            <p
              className={cn(
                "text-[13px] font-medium leading-snug text-foreground line-clamp-2",
                task.status === "Completed" && "text-muted-foreground line-through decoration-muted-foreground/40",
              )}
            >
              {task.title}
            </p>
          </button>

          {task.isRean && (
            <span
              title="Generated by Rean"
              className="flex shrink-0 items-center gap-1 rounded-[3px] border border-foreground/30 bg-foreground/5 px-1.5 py-0.5 text-[10px] font-medium text-foreground"
            >
              <Sparkles className="h-2.5 w-2.5" />
              Rean
            </span>
          )}
        </div>

        {/* Linked entity chip */}
        {task.linkedEntity && (
          <div className="mt-1.5 px-2.5 pl-7">
            <span className="inline-flex items-center gap-1 rounded-[3px] border border-border bg-muted px-1.5 py-0.5 text-[10px] font-medium text-muted-foreground">
              <Link2 className="h-2.5 w-2.5" />
              <span className="tabular">{task.linkedEntity.type}</span>
              <span className="text-foreground/70">·</span>
              <span className="tabular">{task.linkedEntity.name}</span>
            </span>
          </div>
        )}

        {/* Checklist progress */}
        {!compact && prog.total > 0 && (
          <div className="mt-2 px-2.5 pl-7">
            <div className="flex items-center justify-between text-[10px] text-muted-foreground">
              <span className="tabular">
                {prog.done}/{prog.total} checks
              </span>
              <span className="tabular">{prog.pct}%</span>
            </div>
            <div className="mt-1 h-1 w-full overflow-hidden rounded-full bg-muted">
              <div
                className={cn(
                  "h-full rounded-full transition-all",
                  prog.pct === 100 ? "bg-foreground" : "bg-foreground/60",
                )}
                style={{ width: `${prog.pct}%` }}
              />
            </div>
          </div>
        )}

        {/* Bottom row: assignee + due date + comment count */}
        <div className="mt-2.5 flex items-center justify-between gap-2 border-t border-border/60 px-2.5 py-1.5">
          <div className="flex min-w-0 items-center gap-1.5">
            <span
              className="flex h-5 w-5 shrink-0 items-center justify-center rounded-full border border-border bg-muted text-[9px] font-medium text-foreground"
              title={task.assignee}
            >
              {initials(task.assignee)}
            </span>
            <span className="truncate text-[11px] text-muted-foreground">{task.assignee.split(" ")[0]}</span>
          </div>
          <div className="flex items-center gap-2 text-[10px] text-muted-foreground">
            {task.comments && task.comments.length > 0 && (
              <span className="flex items-center gap-0.5 tabular">
                <MessageSquare className="h-2.5 w-2.5" />
                {task.comments.length}
              </span>
            )}
            {task.dueDate && (
              <span
                className={cn(
                  "flex items-center gap-0.5 tabular",
                  due.tone === "overdue" && "text-foreground font-medium",
                  due.tone === "soon" && "text-foreground",
                  due.tone === "none" && "text-muted-foreground/60",
                )}
                title={`Due ${task.dueDate ? new Date(task.dueDate).toLocaleDateString("en-IN") : ""}`}
              >
                <CalendarClock className="h-2.5 w-2.5" />
                {due.text}
              </span>
            )}
          </div>
        </div>

        {/* Rean Accept / Dismiss actions */}
        {task.isRean && (
          <div className="flex items-center gap-1.5 border-t border-border/60 px-2.5 py-1.5">
            <button
              onClick={(e) => {
                e.stopPropagation();
                onAccept?.(task);
              }}
              className="flex h-6 flex-1 items-center justify-center gap-1 rounded-[4px] border border-foreground bg-foreground text-[11px] font-medium text-background hover:bg-foreground/90 transition-colors"
            >
              <Check className="h-3 w-3" />
              Accept
            </button>
            <button
              onClick={(e) => {
                e.stopPropagation();
                onDismiss?.(task);
              }}
              className="flex h-6 flex-1 items-center justify-center gap-1 rounded-[4px] border border-border text-[11px] font-medium text-muted-foreground hover:bg-accent hover:text-foreground transition-colors"
            >
              <X className="h-3 w-3" />
              Dismiss
            </button>
          </div>
        )}
      </div>
    </div>
  );
}
