/* ============================================================
   Logistics-focused Integrations Catalog
   ------------------------------------------------------------
   25+ providers specific to transportation & logistics -
   fleet telematics, 3PL shipping, e-commerce channels, WMS,
   maps & routing, government compliance, fuel cards, banking,
   CRM, email, insurance. All real providers with real docs URLs
   and real integration patterns used by Indian logistics companies.

   Imported by _data.ts → spread into ALL_PROVIDERS + new categories
   added to CATEGORY_META + CATEGORY_ORDER.
   ============================================================ */

import type { IntegrationProvider, IntegrationCategory } from "./_data";

/* ---------- Fleet Telematics (GPS / IoT / ELD) ---------- */
export const FLEET_TELEMATICS_PROVIDERS: IntegrationProvider[] = [
  {
    id: "motive",
    name: "Motive (KeepTruckin)",
    category: "telemetry",
    tagline: "ELD compliance, GPS tracking, dashcams, and driver scorecards.",
    description:
      "Motive is the largest ELD provider in North America and growing fast in India. Pull vehicle location, fuel level, engine hours, harsh events, and driver hours-of-service into Reanzly. Auto-flags HOS violations and risky driving.",
    region: "US",
    docsUrl: "https://developer.motive.com/",
    mark: "MT",
    official: false,
    multiInstance: true,
    sandboxSupported: true,
    pricingSummary: "₹1,499/vehicle/mo",
    fields: [
      { id: "apiKey", label: "API Key", type: "text", placeholder: "live_XXXXXXXX", required: true },
      { id: "apiSecret", label: "API Secret", type: "password", placeholder: "••••••••", required: true, secret: true },
      { id: "webhookUrl", label: "Webhook URL", type: "webhook-url" },
      { id: "companyId", label: "Motive Company ID", type: "text", required: true },
    ],
    capabilities: [
      { label: "GPS location", supported: true },
      { label: "ELD/HOS", supported: true },
      { label: "Fuel level", supported: true },
      { label: "Dashcam events", supported: true },
      { label: "Driver scorecards", supported: true },
      { label: "Engine diagnostics", supported: true },
      { label: "Geofence alerts", supported: true },
      { label: "IFTA reporting", supported: false },
    ],
    usedBy: ["vehicles", "fleet-map", "trips", "fuel-energy", "maintenance", "drivers-staff"],
  },
  {
    id: "samsara",
    name: "Samsara",
    category: "telemetry",
    tagline: "Complete fleet telemetry: GPS, dashcams, trailer tracking, ELD.",
    description:
      "Samsara is the leading enterprise telematics platform. Pull vehicle location, trailer temperature, fuel, driver behaviour, and AI dashcam events. Best for cold-chain and large fleets.",
    region: "US",
    docsUrl: "https://developers.samsara.com/",
    mark: "SM",
    official: false,
    multiInstance: false,
    sandboxSupported: true,
    pricingSummary: "₹2,499/vehicle/mo",
    fields: [
      { id: "apiToken", label: "API Token (bearer)", type: "password", required: true, secret: true },
      { id: "baseUrl", label: "Base URL", type: "select", options: [{ value: "api.samsara.com", label: "Production (api.samsara.com)" }, { value: "api.eu.samsara.com", label: "EU (api.eu.samsara.com)" }] },
      { id: "webhookUrl", label: "Webhook URL", type: "webhook-url" },
    ],
    capabilities: [
      { label: "GPS location", supported: true },
      { label: "ELD/HOS", supported: true },
      { label: "Reefer temperature", supported: true },
      { label: "Dashcam AI events", supported: true },
      { label: "Fuel level", supported: true },
      { label: "Trailer tracking", supported: true },
      { label: "Driver coaching", supported: true },
      { label: "IFTA reporting", supported: true },
    ],
    usedBy: ["vehicles", "fleet-map", "trips", "maintenance", "fuel-energy"],
  },
  {
    id: "quartix",
    name: "Quartix",
    category: "telemetry",
    tagline: "UK-based vehicle tracking with strong India presence.",
    description:
      "Quartix provides GPS tracking with 30-second updates, driver behaviour scoring, and idling reports. Popular with mid-sized Indian fleets wanting a no-frills tracker.",
    region: "GLOBAL",
    docsUrl: "https://www.quartix.com/en-gb/developers",
    mark: "QX",
    official: false,
    multiInstance: false,
    sandboxSupported: false,
    pricingSummary: "₹899/vehicle/mo",
    fields: [
      { id: "account", label: "Account ID", type: "text", required: true },
      { id: "username", label: "Username", type: "text", required: true },
      { id: "password", label: "Password", type: "password", required: true, secret: true },
    ],
    capabilities: [
      { label: "GPS location", supported: true },
      { label: "Idle reporting", supported: true },
      { label: "Driver behaviour", supported: true },
      { label: "Geofences", supported: true },
      { label: "ELD/HOS", supported: false },
      { label: "Fuel level", supported: false },
      { label: "Dashcam", supported: false },
      { label: "Reefer", supported: false },
    ],
    usedBy: ["vehicles", "fleet-map"],
  },
  {
    id: "webfleet",
    name: "WEBFLEET (TomTom)",
    category: "telemetry",
    tagline: "TomTom's enterprise fleet platform. EU + India.",
    description:
      "WEBFLEET by TomTom is a leading European telematics platform. Track vehicles, optimise routes, monitor driver behaviour, and integrate with TomTom traffic for ETA prediction.",
    region: "GLOBAL",
    docsUrl: "https://developer.tomtom.com/webfleet-connect",
    mark: "WF",
    official: false,
    multiInstance: false,
    sandboxSupported: true,
    pricingSummary: "₹1,200/vehicle/mo",
    fields: [
      { id: "account", label: "WEBFLEET Account", type: "text", required: true },
      { id: "username", label: "Username", type: "text", required: true },
      { id: "password", label: "Password", type: "password", required: true, secret: true },
      { id: "apiKey", label: "API Key", type: "password", required: true, secret: true },
    ],
    capabilities: [
      { label: "GPS location", supported: true },
      { label: "Route optimisation", supported: true },
      { label: "Driver behaviour", supported: true },
      { label: "Traffic-aware ETA", supported: true },
      { label: "Order dispatch to PND", supported: true },
      { label: "ELD/HOS", supported: false },
      { label: "Reefer", supported: false },
      { label: "Dashcam", supported: false },
    ],
    usedBy: ["vehicles", "fleet-map", "trips"],
  },
  {
    id: "verizon-connect",
    name: "Verizon Connect",
    category: "telemetry",
    tagline: "Enterprise fleet management from Verizon.",
    description:
      "Verizon Connect (formerly Networkfleet) provides GPS tracking, ELD compliance, dashcams, and asset tracking. Enterprise-grade with deep reporting.",
    region: "US",
    docsUrl: "https://www.verizonconnect.com/resources/api/",
    mark: "VC",
    official: false,
    multiInstance: false,
    sandboxSupported: true,
    pricingSummary: "Custom enterprise pricing",
    fields: [
      { id: "apiKey", label: "API Key", type: "text", required: true },
      { id: "apiSecret", label: "API Secret", type: "password", required: true, secret: true },
    ],
    capabilities: [
      { label: "GPS location", supported: true },
      { label: "ELD/HOS", supported: true },
      { label: "Asset tracking", supported: true },
      { label: "Dashcam AI", supported: true },
      { label: "Fuel cards", supported: true },
      { label: "Maintenance scheduling", supported: true },
      { label: "Reefer", supported: false },
      { label: "IFTA reporting", supported: true },
    ],
    usedBy: ["vehicles", "fleet-map", "maintenance", "drivers-staff"],
  },
  {
    id: "tracko-mahindra",
    name: "Mahindra Tracko",
    category: "telemetry",
    tagline: "Indian OEM-grade vehicle tracking from Mahindra.",
    description:
      "Mahindra Tracko is the telematics service from Mahindra & Mahindra, designed for Indian trucks and operating conditions. Provides GPS, fuel sensors, ignition cut-off, and AC on/off detection.",
    region: "IN",
    docsUrl: "https://www.tracko.in/api-docs",
    mark: "TK",
    official: false,
    multiInstance: false,
    sandboxSupported: false,
    pricingSummary: "₹499/vehicle/mo",
    fields: [
      { id: "apiUser", label: "API User", type: "text", required: true },
      { id: "apiKey", label: "API Key", type: "password", required: true, secret: true },
      { id: "clientId", label: "Client ID", type: "text", required: true },
    ],
    capabilities: [
      { label: "GPS location", supported: true },
      { label: "Fuel sensor", supported: true },
      { label: "Ignition cut-off", supported: true },
      { label: "AC on/off", supported: true },
      { label: "Geofence", supported: true },
      { label: "ELD/HOS", supported: false },
      { label: "Dashcam", supported: false },
      { label: "Reefer", supported: false },
    ],
    usedBy: ["vehicles", "fleet-map", "fuel-energy"],
  },
  {
    id: "roambee",
    name: "Roambee",
    category: "telemetry",
    tagline: "Cargo, pallet, and container tracking with IoT bees.",
    description:
      "Roambee provides IoT-based shipment, pallet, and container tracking with temperature, humidity, shock, and light sensors. Best for high-value cargo, pharma cold chain, and global container tracking.",
    region: "US",
    docsUrl: "https://www.roambee.com/developers",
    mark: "RB",
    official: false,
    multiInstance: true,
    sandboxSupported: true,
    pricingSummary: "₹3,500/bee/mo",
    fields: [
      { id: "apiKey", label: "API Key", type: "password", required: true, secret: true },
      { id: "accountName", label: "Account Name", type: "text", required: true },
      { id: "webhookUrl", label: "Shipment Event Webhook", type: "webhook-url" },
    ],
    capabilities: [
      { label: "Cargo tracking", supported: true },
      { label: "Container tracking", supported: true },
      { label: "Temperature", supported: true },
      { label: "Humidity", supported: true },
      { label: "Shock events", supported: true },
      { label: "Light events (tamper)", supported: true },
      { label: "Geofence", supported: true },
      { label: "Cross-border customs", supported: true },
    ],
    usedBy: ["fleet-map", "trips", "issues", "compliance"],
  },
];

/* ---------- 3PL Shipping Platforms ---------- */
export const LOGISTICS_PLATFORM_PROVIDERS: IntegrationProvider[] = [
  {
    id: "shiprocket",
    name: "Shiprocket",
    category: "logistics",
    tagline: "India's largest 3PL aggregator - 17+ courier partners.",
    description:
      "Shiprocket aggregates 17+ courier partners (Bluedart, Delhivery, Ecom Express, Xpressbees, etc.). Push orders from Reanzly to Shiprocket, auto-allocate the cheapest courier, print labels, and track shipments end-to-end.",
    region: "IN",
    docsUrl: "https://apidocs.shiprocket.in/",
    mark: "SR",
    official: true,
    multiInstance: false,
    sandboxSupported: true,
    pricingSummary: "₹19/shipment + courier rates",
    fields: [
      { id: "email", label: "Email", type: "text", required: true },
      { id: "password", label: "Password", type: "password", required: true, secret: true },
      { id: "token", label: "Cached Token", type: "password", secret: true, helpText: "Auto-refreshed every 24h." },
      { id: "webhookUrl", label: "Shipment Status Webhook", type: "webhook-url" },
    ],
    capabilities: [
      { label: "Order push", supported: true },
      { label: "Courier allocation", supported: true },
      { label: "Label print", supported: true },
      { label: "Manifest", supported: true },
      { label: "Pickup schedule", supported: true },
      { label: "NDR (RTO)", supported: true },
      { label: "Tracking webhook", supported: true },
      { label: "International", supported: true },
    ],
    usedBy: ["trips", "customers", "pod", "invoice"],
  },
  {
    id: "delhivery",
    name: "Delhivery Direct API",
    category: "logistics",
    tagline: "Direct API with Delhivery - India's largest 3PL.",
    description:
      "Bypass aggregators and integrate directly with Delhivery. Push orders, generate AWBs, schedule pickups, and pull tracking. Best for high-volume shippers (>5,000 parcels/day).",
    region: "IN",
    docsUrl: "https://developers.delhivery.com/",
    mark: "DH",
    official: false,
    multiInstance: false,
    sandboxSupported: true,
    pricingSummary: "Volume-based, ₹18-32/parcel",
    fields: [
      { id: "apiToken", label: "API Token", type: "password", required: true, secret: true },
      { id: "clientName", label: "Client Name", type: "text", required: true },
      { id: "environment", label: "Environment", type: "select", required: true, options: [{ value: "production", label: "Production" }, { value: "staging", label: "Staging" }] },
      { id: "webhookUrl", label: "Tracking Webhook", type: "webhook-url" },
    ],
    capabilities: [
      { label: "Order push", supported: true },
      { label: "AWB generation", supported: true },
      { label: "Pickup schedule", supported: true },
      { label: "Tracking webhook", supported: true },
      { label: "RTO management", supported: true },
      { label: "Warehouse", supported: true },
      { label: "Cross-border", supported: true },
      { label: "Heavy/Cargo", supported: true },
    ],
    usedBy: ["trips", "customers", "pod", "warehouse"],
  },
  {
    id: "bluedart",
    name: "BlueDart",
    category: "logistics",
    tagline: "DHL-owned Indian express carrier.",
    description:
      "Direct API with BlueDart for air-express domestic and international. Generate Waybills, schedule pickups, and pull pickup tracking. Best for high-value and time-critical parcels.",
    region: "IN",
    docsUrl: "https://www.bluedart.com/api",
    mark: "BD",
    official: false,
    multiInstance: false,
    sandboxSupported: false,
    pricingSummary: "Volume-based, ₹40-80/parcel",
    fields: [
      { id: "apiToken", label: "API Token", type: "password", required: true, secret: true },
      { id: "licenceKey", label: "Licence Key", type: "password", required: true, secret: true },
      { id: "loginId", label: "Login ID", type: "text", required: true },
    ],
    capabilities: [
      { label: "Waybill generation", supported: true },
      { label: "Pickup schedule", supported: true },
      { label: "Pincode serviceability", supported: true },
      { label: "Rate calculator", supported: true },
      { label: "Tracking", supported: true },
      { label: "International", supported: true },
      { label: "Reverse pickup", supported: true },
      { label: "COD remit", supported: true },
    ],
    usedBy: ["trips", "customers", "pod"],
  },
  {
    id: "ecom-express",
    name: "Ecom Express",
    category: "logistics",
    tagline: "Indian e-commerce-focused 3PL with COD expertise.",
    description:
      "Ecom Express specialises in e-commerce parcel delivery with strong COD remittance and reverse logistics. Push orders, generate AWBs, and pull tracking.",
    region: "IN",
    docsUrl: "https://api.ecomexpress.in/",
    mark: "EE",
    official: false,
    multiInstance: false,
    sandboxSupported: true,
    pricingSummary: "₹20-35/parcel",
    fields: [
      { id: "username", label: "API Username", type: "text", required: true },
      { id: "password", label: "API Password", type: "password", required: true, secret: true },
      { id: "access_token", label: "Access Token", type: "password", secret: true },
    ],
    capabilities: [
      { label: "Order push", supported: true },
      { label: "AWB generation", supported: true },
      { label: "Pickup", supported: true },
      { label: "Tracking", supported: true },
      { label: "COD remit", supported: true },
      { label: "Reverse logistics", supported: true },
      { label: "International", supported: false },
      { label: "Heavy/Cargo", supported: false },
    ],
    usedBy: ["trips", "customers", "pod"],
  },
  {
    id: "xpressbees",
    name: "Xpressbees",
    category: "logistics",
    tagline: "First-Cry-born Indian 3PL. Strong B2C reach.",
    description:
      "Xpressbees provides e-commerce parcel delivery across 2,500+ Indian cities. Push orders, generate AWBs, schedule pickups, and pull tracking events.",
    region: "IN",
    docsUrl: "https://doc.xpressbees.com/",
    mark: "XB",
    official: false,
    multiInstance: false,
    sandboxSupported: true,
    pricingSummary: "₹18-32/parcel",
    fields: [
      { id: "userId", label: "User ID", type: "text", required: true },
      { id: "apiKey", label: "API Key", type: "password", required: true, secret: true },
    ],
    capabilities: [
      { label: "Order push", supported: true },
      { label: "AWB generation", supported: true },
      { label: "Pickup", supported: true },
      { label: "Tracking", supported: true },
      { label: "COD remit", supported: true },
      { label: "Reverse", supported: true },
      { label: "Heavy/Cargo", supported: false },
      { label: "International", supported: false },
    ],
    usedBy: ["trips", "customers", "pod"],
  },
];

/* ---------- E-commerce Channels ---------- */
export const ECOMMERCE_PROVIDERS: IntegrationProvider[] = [
  {
    id: "amazon-seller",
    name: "Amazon Seller Central",
    category: "ecommerce",
    tagline: "Pull Amazon orders, push shipment confirmations & invoices.",
    description:
      "Amazon SP-API integration. Pull MCF and FBA orders, sync inventory, push shipment confirmations (with tracking), and download settlement reports automatically.",
    region: "GLOBAL",
    docsUrl: "https://developer-docs.amazon.com/sp-api/",
    mark: "AZ",
    official: false,
    multiInstance: true,
    sandboxSupported: true,
    pricingSummary: "Free for sellers · AWS costs apply",
    fields: [
      { id: "refreshToken", label: "Refresh Token", type: "password", required: true, secret: true },
      { id: "lwaClientId", label: "LWA Client ID", type: "text", required: true },
      { id: "lwaClientSecret", label: "LWA Client Secret", type: "password", required: true, secret: true },
      { id: "sellerId", label: "Seller ID (Merchant Token)", type: "text", required: true },
      { id: "marketplaceId", label: "Marketplace ID", type: "select", options: [{ value: "A21TJRUUN4KGV", label: "India (A21TJRUUN4KGV)" }, { value: "ATVPDKIKX0DER", label: "US (ATVPDKIKX0DER)" }, { value: "A1F83G8C2ARO7P", label: "UK (A1F83G8C2ARO7P)" }] },
      { id: "awsRegion", label: "AWS Region", type: "select", options: [{ value: "eu-west-1", label: "eu-west-1" }, { value: "us-east-1", label: "us-east-1" }, { value: "us-west-2", label: "us-west-2" }] },
      { id: "roleArn", label: "AWS Role ARN", type: "text", required: true },
    ],
    capabilities: [
      { label: "Order pull", supported: true },
      { label: "Shipment confirmation", supported: true },
      { label: "Inventory sync", supported: true },
      { label: "Settlement reports", supported: true },
      { label: "FBA/MCF", supported: true },
      { label: "Returns", supported: true },
      { label: "Sponsored Products", supported: false },
      { label: "Vendor Central", supported: false },
    ],
    usedBy: ["trips", "customers", "invoice", "warehouse"],
  },
  {
    id: "flipkart-seller",
    name: "Flipkart Seller",
    category: "ecommerce",
    tagline: "Pull Flipkart orders, push shipments & invoices.",
    description:
      "Flipkart Seller API integration. Pull orders, sync inventory, push shipment confirmations with tracking IDs, and download settlement reports.",
    region: "IN",
    docsUrl: "https://seller.flipkart.com/api-docs/",
    mark: "FK",
    official: false,
    multiInstance: false,
    sandboxSupported: true,
    pricingSummary: "Free for sellers",
    fields: [
      { id: "clientId", label: "Client ID", type: "text", required: true },
      { id: "clientSecret", label: "Client Secret", type: "password", required: true, secret: true },
      { id: "sellerId", label: "Seller ID", type: "text", required: true },
      { id: "environment", label: "Environment", type: "select", required: true, options: [{ value: "production", label: "Production" }, { value: "sandbox", label: "Sandbox (Flipkart dev)" }] },
    ],
    capabilities: [
      { label: "Order pull", supported: true },
      { label: "Shipment confirmation", supported: true },
      { label: "Inventory sync", supported: true },
      { label: "Settlement reports", supported: true },
      { label: "Returns", supported: true },
      { label: "F-Assured", supported: true },
      { label: "Cross-border", supported: false },
      { label: "Vendor", supported: false },
    ],
    usedBy: ["trips", "customers", "invoice", "warehouse"],
  },
  {
    id: "shopify",
    name: "Shopify",
    category: "ecommerce",
    tagline: "Sync Shopify orders, fulfillments, and inventory.",
    description:
      "Shopify Storefront + Admin API. Pull orders, push fulfillments with tracking, sync inventory, and trigger customer notifications when shipments dispatch.",
    region: "GLOBAL",
    docsUrl: "https://shopify.dev/docs/api",
    mark: "SH",
    official: false,
    multiInstance: true,
    sandboxSupported: true,
    pricingSummary: "Free with Shopify plan",
    fields: [
      { id: "shopDomain", label: "Shop Domain", type: "text", placeholder: "your-store.myshopify.com", required: true },
      { id: "accessToken", label: "Admin API Access Token", type: "password", placeholder: "shpat_XXXXXXXX", required: true, secret: true },
      { id: "apiVersion", label: "API Version", type: "select", options: [{ value: "2024-10", label: "2024-10 (stable)" }, { value: "2024-07", label: "2024-07" }, { value: "2025-01", label: "2025-01 (release candidate)" }] },
      { id: "webhookUrl", label: "Webhook URL", type: "webhook-url" },
    ],
    capabilities: [
      { label: "Order pull", supported: true },
      { label: "Fulfillment create", supported: true },
      { label: "Inventory sync", supported: true },
      { label: "Customer sync", supported: true },
      { label: "Returns", supported: true },
      { label: "Multi-location", supported: true },
      { label: "B2B", supported: true },
      { label: "POS", supported: false },
    ],
    usedBy: ["trips", "customers", "invoice", "warehouse"],
  },
];

/* ---------- Warehouse / WMS ---------- */
export const WAREHOUSE_PROVIDERS: IntegrationProvider[] = [
  {
    id: "unicommerce",
    name: "Unicommerce",
    category: "warehouse",
    tagline: "India's leading omni-channel WMS and OMS.",
    description:
      "Unicommerce is an omni-channel enablement platform. Sync inventory across warehouses, marketplaces, and stores. Push picklists, get shipping manifests, and pull return requests.",
    region: "IN",
    docsUrl: "https://documentation.unicommerce.com/",
    mark: "UC",
    official: false,
    multiInstance: false,
    sandboxSupported: true,
    pricingSummary: "₹3,999/mo per warehouse",
    fields: [
      { id: "apiUsername", label: "API Username", type: "text", required: true },
      { id: "apiPassword", label: "API Password", type: "password", required: true, secret: true },
      { id: "facilityCode", label: "Facility Code", type: "text", required: true },
      { id: "environment", label: "Environment", type: "select", required: true, options: [{ value: "production", label: "Production" }, { value: "stage", label: "Staging" }] },
    ],
    capabilities: [
      { label: "Inventory sync", supported: true },
      { label: "Picklist", supported: true },
      { label: "Manifest", supported: true },
      { label: "Returns", supported: true },
      { label: "Multi-warehouse", supported: true },
      { label: "Marketplace sync", supported: true },
      { label: "B2B orders", supported: true },
      { label: "Cold storage", supported: false },
    ],
    usedBy: ["warehouse", "trips", "pod"],
  },
  {
    id: "zoho-inventory",
    name: "Zoho Inventory",
    category: "warehouse",
    tagline: "Inventory, order management, and multi-channel selling.",
    description:
      "Zoho Inventory handles inventory tracking, order management, and multi-channel sales. Sync stock levels, push sales orders, and pull purchase orders.",
    region: "GLOBAL",
    docsUrl: "https://www.zoho.com/inventory/api/v1/",
    mark: "ZI",
    official: false,
    multiInstance: false,
    sandboxSupported: true,
    pricingSummary: "₹2,499/mo",
    fields: [
      { id: "authToken", label: "Auth Token", type: "password", required: true, secret: true },
      { id: "organizationId", label: "Organization ID", type: "text", required: true },
    ],
    capabilities: [
      { label: "Inventory sync", supported: true },
      { label: "Sales orders", supported: true },
      { label: "Purchase orders", supported: true },
      { label: "Multi-warehouse", supported: true },
      { label: "Marketplace sync", supported: true },
      { label: "Serial/batch tracking", supported: true },
      { label: "Bundles", supported: true },
      { label: "Cold storage", supported: false },
    ],
    usedBy: ["warehouse", "customers", "vendors"],
  },
  {
    id: "easyecom",
    name: "EasyEcom",
    category: "warehouse",
    tagline: "Unified inventory + 3PL sync for D2C brands.",
    description:
      "EasyEcom is a unified inventory management platform for D2C brands. Sync inventory across marketplaces, D2C stores, and 3PL warehouses. Reconcile settlements automatically.",
    region: "IN",
    docsUrl: "https://docs.easyecom.io/",
    mark: "EC",
    official: false,
    multiInstance: false,
    sandboxSupported: false,
    pricingSummary: "₹2,999/mo",
    fields: [
      { id: "apiToken", label: "API Token", type: "password", required: true, secret: true },
      { id: "clientCode", label: "Client Code", type: "text", required: true },
    ],
    capabilities: [
      { label: "Inventory sync", supported: true },
      { label: "Marketplace sync", supported: true },
      { label: "3PL sync", supported: true },
      { label: "Settlement reconciliation", supported: true },
      { label: "Returns", supported: true },
      { label: "B2B orders", supported: false },
      { label: "Cold storage", supported: false },
      { label: "POS", supported: false },
    ],
    usedBy: ["warehouse", "customers"],
  },
];

/* ---------- Maps & Routing ---------- */
export const MAPS_PROVIDERS: IntegrationProvider[] = [
  {
    id: "google-maps",
    name: "Google Maps Platform",
    category: "maps",
    tagline: "Geocoding, Directions, Distance Matrix, Places, Roads.",
    description:
      "Google Maps Platform is the gold standard for maps, geocoding, and routing. Used by Reanzly for ETA calculation, distance matrix optimisation, geofencing, and address autocomplete.",
    region: "GLOBAL",
    docsUrl: "https://developers.google.com/maps/documentation",
    mark: "GM",
    official: true,
    multiInstance: false,
    sandboxSupported: false,
    pricingSummary: "$200/mo free credit · ₹5.6/km route",
    fields: [
      { id: "apiKey", label: "API Key", type: "password", required: true, secret: true },
      { id: "projectId", label: "GCP Project ID", type: "text", required: true },
      { id: "restrictReferrer", label: "HTTP Referrer Restriction", type: "text", placeholder: "reanzly.com/*", helpText: "Restrict the key to your domain." },
    ],
    capabilities: [
      { label: "Geocoding", supported: true },
      { label: "Reverse geocoding", supported: true },
      { label: "Directions", supported: true },
      { label: "Distance Matrix", supported: true },
      { label: "Places", supported: true },
      { label: "Roads API (snap-to-road)", supported: true },
      { label: "Time Zone", supported: true },
      { label: "Address validation", supported: true },
    ],
    usedBy: ["fleet-map", "trips", "customers", "vehicles", "warehouse"],
  },
  {
    id: "mapbox",
    name: "Mapbox",
    category: "maps",
    tagline: "Custom maps, navigation, and geospatial analytics.",
    description:
      "Mapbox provides customisable maps, the Mapbox Directions API with traffic-aware routing, and Matrix API for solving vehicle routing problems at scale.",
    region: "GLOBAL",
    docsUrl: "https://docs.mapbox.com/api/",
    mark: "MB",
    official: false,
    multiInstance: false,
    sandboxSupported: true,
    pricingSummary: "50K free loads/mo · pay-as-you-go",
    fields: [
      { id: "accessToken", label: "Public Access Token", type: "text", required: true },
      { id: "secretToken", label: "Secret Token (server-side)", type: "password", required: true, secret: true },
    ],
    capabilities: [
      { label: "Maps SDK", supported: true },
      { label: "Directions", supported: true },
      { label: "Matrix API", supported: true },
      { label: "Geocoding", supported: true },
      { label: "Isochrones", supported: true },
      { label: "Tile queries", supported: true },
      { label: "Vision (dashcam SDK)", supported: true },
      { label: "Address validation", supported: false },
    ],
    usedBy: ["fleet-map", "trips", "customers"],
  },
  {
    id: "here",
    name: "HERE Technologies",
    category: "maps",
    tagline: "Enterprise maps, routing, and truck-specific attributes.",
    description:
      "HERE provides enterprise maps with truck-specific routing (height, weight, hazmat restrictions) - best for heavy vehicles and cross-border logistics.",
    region: "GLOBAL",
    docsUrl: "https://developer.here.com/",
    mark: "HE",
    official: false,
    multiInstance: false,
    sandboxSupported: true,
    pricingSummary: "Free tier · ₹4.2/km truck route",
    fields: [
      { id: "apiKey", label: "API Key", type: "password", required: true, secret: true },
      { id: "appId", label: "App ID", type: "text", required: true },
    ],
    capabilities: [
      { label: "Maps SDK", supported: true },
      { label: "Truck routing", supported: true },
      { label: "Hazmat routing", supported: true },
      { label: "Matrix", supported: true },
      { label: "Geocoding", supported: true },
      { label: "Traffic", supported: true },
      { label: "Positioning", supported: true },
      { label: "Weather", supported: true },
    ],
    usedBy: ["fleet-map", "trips", "vehicles"],
  },
];

/* ---------- Government & Compliance ---------- */

/** States & UTs of India - shared by the govt portal providers below. */
export const IN_STATES = [
  { value: "AN", label: "Andaman & Nicobar Islands" },
  { value: "AP", label: "Andhra Pradesh" },
  { value: "AR", label: "Arunachal Pradesh" },
  { value: "AS", label: "Assam" },
  { value: "BR", label: "Bihar" },
  { value: "CH", label: "Chandigarh" },
  { value: "CT", label: "Chhattisgarh" },
  { value: "DD", label: "Daman & Diu" },
  { value: "DL", label: "Delhi" },
  { value: "GA", label: "Goa" },
  { value: "GJ", label: "Gujarat" },
  { value: "HP", label: "Himachal Pradesh" },
  { value: "HR", label: "Haryana" },
  { value: "JH", label: "Jharkhand" },
  { value: "JK", label: "Jammu & Kashmir" },
  { value: "KA", label: "Karnataka" },
  { value: "KL", label: "Kerala" },
  { value: "LA", label: "Ladakh" },
  { value: "LD", label: "Lakshadweep" },
  { value: "MH", label: "Maharashtra" },
  { value: "ML", label: "Meghalaya" },
  { value: "MN", label: "Manipur" },
  { value: "MP", label: "Madhya Pradesh" },
  { value: "MZ", label: "Mizoram" },
  { value: "NL", label: "Nagaland" },
  { value: "OD", label: "Odisha" },
  { value: "PB", label: "Punjab" },
  { value: "PY", label: "Puducherry" },
  { value: "RJ", label: "Rajasthan" },
  { value: "SK", label: "Sikkim" },
  { value: "TG", label: "Telangana" },
  { value: "TN", label: "Tamil Nadu" },
  { value: "TR", label: "Tripura" },
  { value: "UP", label: "Uttar Pradesh" },
  { value: "UT", label: "Uttarakhand" },
  { value: "WB", label: "West Bengal" },
];

export const GOV_PROVIDERS: IntegrationProvider[] = [
  {
    id: "vahan",
    name: "VAHAN (MoRTH)",
    category: "gov",
    tagline: "Verify vehicle registration, fitness, and pollution status.",
    description:
      "VAHAN is the central vehicle registry by MoRTH. Pull vehicle registration, fitness validity, insurance status, pollution (PUC) status, and permit details directly from the source. Reanzly runs nightly reconciliation across the entire fleet and raises alerts when fitness, insurance or PUC approach expiry.",
    region: "IN",
    docsUrl: "https://vahan.parivahan.gov.in/",
    mark: "VH",
    official: true,
    multiInstance: false,
    sandboxSupported: false,
    pricingSummary: "₹5/lookup · bulk API access",
    fields: [
      { id: "apiToken", label: "API Token (Parivahan)", type: "password", required: true, secret: true },
      { id: "agencyCode", label: "Agency Code", type: "text", required: true, helpText: "Allotted by NIC for your business." },
    ],
    capabilities: [
      { label: "RC verification", supported: true },
      { label: "Fitness validity", supported: true },
      { label: "Insurance status", supported: true },
      { label: "PUC status", supported: true },
      { label: "Permit details", supported: true },
      { label: "National permit", supported: true },
      { label: "Ownership transfer", supported: false },
      { label: "Tax payment", supported: false },
    ],
    usedBy: ["vehicles", "compliance", "inspection"],
    syncConfig: {
      frequency: "daily",
      onDemand: true,
      typicalRecordsPerSync: 28,
      syncData: [
        { description: "RC + fitness + insurance status per vehicle -> vehicles.compliance", direction: "pull" },
        { description: "PUC expiry dates -> compliance.expiry calendar", direction: "pull" },
        { description: "Permit type + validity -> vehicles.permits", direction: "pull" },
      ],
    },
  },
  {
    id: "icegate",
    name: "ICEGATE (Customs)",
    category: "gov",
    tagline: "Indian Customs EDI - filing, shipping bill, BOE status, RoDTEP.",
    description:
      "ICEGATE is the Indian Customs EDI System operated by CBIC. File shipping bills, bill of entries, track status, pull customs duty payment receipts, claim RoDTEP and RoSCTL scrips, and reconcile EGM/IGM against your lorry receipts. Essential for cross-border logistics and CHA workflows.",
    region: "IN",
    docsUrl: "https://www.icegate.gov.in/",
    mark: "IC",
    official: true,
    multiInstance: false,
    sandboxSupported: true,
    pricingSummary: "Free (govt API)",
    fields: [
      { id: "icegateId", label: "ICEGATE User ID", type: "text", required: true },
      { id: "password", label: "Password", type: "password", required: true, secret: true },
      { id: "iecCode", label: "IEC Code", type: "text", required: true, placeholder: "10-digit IEC" },
    ],
    capabilities: [
      { label: "Shipping bill filing", supported: true },
      { label: "Bill of entry", supported: true },
      { label: "Duty payment receipt", supported: true },
      { label: "Status tracking", supported: true },
      { label: "EGM/IGM", supported: true },
      { label: "DGFT sync", supported: true },
      { label: "RoDTEP / RoSCTL", supported: true },
      { label: "SCR / SVB", supported: true },
      { label: "Customs EDI", supported: true },
      { label: "e-Sanchit (document upload)", supported: true },
    ],
    usedBy: ["trips", "compliance", "invoice"],
    syncConfig: {
      frequency: "hourly",
      onDemand: true,
      typicalRecordsPerSync: 12,
      syncData: [
        { description: "Shipping bill status -> invoice.export docs", direction: "pull" },
        { description: "BOE duty challan -> expenses.customs", direction: "pull" },
        { description: "EGM/IGM -> trips.cross-border milestone", direction: "pull" },
        { description: "RoDTEP scrip credit -> ledger.incentives", direction: "pull" },
      ],
    },
  },
  {
    id: "digilocker",
    name: "DigiLocker",
    category: "gov",
    tagline: "Pull government-issued documents with user consent.",
    description:
      "DigiLocker is the official document wallet by MeitY. With user consent, pull Aadhaar, PAN, driving licence, RC, and insurance certificates - eliminating manual uploads. Driver onboarding becomes a one-tap flow instead of a 7-document scan queue.",
    region: "IN",
    docsUrl: "https://apis.digitalgov.in/",
    mark: "DL",
    official: true,
    multiInstance: false,
    sandboxSupported: true,
    pricingSummary: "Free (govt API)",
    fields: [
      { id: "clientId", label: "Client ID", type: "text", required: true },
      { id: "clientSecret", label: "Client Secret", type: "password", required: true, secret: true },
      { id: "redirectUri", label: "OAuth Redirect URI", type: "text", required: true, placeholder: "https://your-reanzly.com/api/oauth/digilocker" },
    ],
    capabilities: [
      { label: "Aadhaar pull", supported: true },
      { label: "PAN pull", supported: true },
      { label: "Driving licence", supported: true },
      { label: "RC (vehicle)", supported: true },
      { label: "Insurance", supported: true },
      { label: "Class X/XII marksheets", supported: true },
      { label: "Push to wallet", supported: true },
      { label: "e-KYC", supported: true },
    ],
    usedBy: ["drivers-staff", "vehicles", "compliance", "documents"],
    syncConfig: {
      frequency: "on-demand",
      onDemand: true,
      typicalRecordsPerSync: 5,
      syncData: [
        { description: "Driver KYC docs -> driver.documents", direction: "pull" },
        { description: "Vehicle RC/insurance -> vehicles.documents", direction: "pull" },
      ],
    },
  },
  {
    id: "gstn",
    name: "GST Network (GSTN)",
    category: "gov",
    tagline: "File GSTR-1/3B, pull GSTR-2A/2B, reconcile ITC, pay tax.",
    description:
      "GSTN is the backbone of the GST regime. File GSTR-1 (outward supplies), GSTR-3B (monthly summary), and GSTR-9 (annual return) directly from Reanzly. Auto-pull GSTR-2A/2B to reconcile Input Tax Credit (ITC) against your purchase register - unmatched ITC rows are surfaced for vendor follow-up. Pay tax via the integrated GST portal and pull challan + ARN receipts back into the ledger.",
    region: "IN",
    docsUrl: "https://www.gst.gov.in/",
    mark: "GS",
    official: true,
    multiInstance: true,
    sandboxSupported: true,
    pricingSummary: "Free (govt API)",
    entityIdLabel: "GSTIN",
    requiresRegion: true,
    filingFrequencies: ["Monthly", "Quarterly (QRMP)", "Annual"],
    fields: [
      { id: "gstin", label: "GSTIN", type: "text", required: true, placeholder: "27ABCDE1234F1Z5", helpText: "15-digit GST Identification Number." },
      { id: "gstUsername", label: "GST Portal Username", type: "text", required: true },
      { id: "gstPassword", label: "GST Portal Password", type: "password", required: true, secret: true },
      { id: "state", label: "State / UT", type: "select", required: true, options: IN_STATES },
      { id: "filingFrequency", label: "Filing Frequency", type: "select", required: true, options: [
        { value: "Monthly", label: "Monthly" },
        { value: "QRMP", label: "Quarterly (QRMP)" },
        { value: "Annual", label: "Annual (GSTR-9)" },
      ] },
      { id: "otpMode", label: "OTP / 2FA Mode", type: "select", options: [
        { value: "sms", label: "SMS OTP" },
        { value: "email", label: "Email OTP" },
        { value: "totp", label: "TOTP (auto)" },
      ] },
    ],
    capabilities: [
      { label: "GSTR-1 filing", supported: true },
      { label: "GSTR-3B filing", supported: true },
      { label: "GSTR-2B pull", supported: true },
      { label: "GSTR-2A reconciliation", supported: true },
      { label: "GSTR-9 annual return", supported: true },
      { label: "Tax payment (PMT-06)", supported: true },
      { label: "e-Invoice (IRP)", supported: true },
      { label: "e-Way Bill (cross-link)", supported: true },
      { label: "Return status track", supported: true },
      { label: "ITC match engine", supported: true },
    ],
    usedBy: ["invoice", "ledger", "compliance", "expenses", "superadmin-billing"],
    syncConfig: {
      frequency: "daily",
      onDemand: true,
      typicalRecordsPerSync: 184,
      syncData: [
        { description: "GSTR-2A line items -> purchase register (ITC reconciliation)", direction: "pull" },
        { description: "GSTR-2B finalized ITC -> ledger.itc_accepted", direction: "pull" },
        { description: "Sales register -> GSTR-1 draft (auto-prep)", direction: "push" },
        { description: "GSTR-3B summary + challan -> compliance.returns", direction: "push" },
        { description: "Return status + ARN -> compliance.filing_log", direction: "pull" },
      ],
    },
  },
  {
    id: "epfo",
    name: "EPFO (Provident Fund)",
    category: "gov",
    tagline: "File ECR, generate challan, sync member master, view PF balance.",
    description:
      "EPFO runs the Employees' Provident Fund scheme. File the Electronic Challan cum Return (ECR) monthly, generate the challan, and pay via the integrated payment portal. Reanzly syncs your member master (UAN to employee mapping) so new joiners are auto-enrolled and exited employees are marked for final settlement. Pull PF balance and passbook entries per UAN for the payroll module.",
    region: "IN",
    docsUrl: "https://unifiedportal-epfo.epfindia.gov.in/",
    mark: "EP",
    official: true,
    multiInstance: false,
    sandboxSupported: false,
    pricingSummary: "Free (govt portal)",
    entityIdLabel: "Establishment Code",
    requiresRegion: true,
    filingFrequencies: ["Monthly"],
    fields: [
      { id: "establishmentCode", label: "Establishment Code", type: "text", required: true, placeholder: "MHBAN0012345000", helpText: "Includes region + office code + establishment + extension." },
      { id: "epfoUsername", label: "EPFO Username", type: "text", required: true },
      { id: "epfoPassword", label: "EPFO Password", type: "password", required: true, secret: true },
      { id: "state", label: "State / UT", type: "select", required: true, options: IN_STATES },
      { id: "uanSeed", label: "UAN Seed Range (optional)", type: "text", placeholder: "100000000000-100000000999", helpText: "Optional - used to bulk-allot UANs for new joiners." },
    ],
    capabilities: [
      { label: "ECR filing", supported: true },
      { label: "Challan generation (PMT-06)", supported: true },
      { label: "PF balance pull", supported: true },
      { label: "Member master sync", supported: true },
      { label: "UAN allotment", supported: true },
      { label: "KYC update (Aadhaar/PAN/Bank)", supported: true },
      { label: "Form 5/10 (join/exit)", supported: true },
      { label: "Transfer claim (Form 13)", supported: true },
      { label: "Passbook pull", supported: true },
      { label: "e-Nomination", supported: true },
    ],
    usedBy: ["payroll", "hr", "compliance", "employees"],
    syncConfig: {
      frequency: "daily",
      onDemand: true,
      typicalRecordsPerSync: 45,
      syncData: [
        { description: "ECR monthly return -> EPFO portal", direction: "push" },
        { description: "Member master (UAN, name, DOB, DOJ) -> employee.epfo_profile", direction: "pull" },
        { description: "Challan + TRRN receipt -> compliance.returns", direction: "pull" },
        { description: "PF passbook entries -> ledger.pf_balance", direction: "pull" },
        { description: "Joiners/exiters -> Form 5/10 queue", direction: "push" },
      ],
    },
  },
  {
    id: "esic",
    name: "ESIC (Employees' State Insurance)",
    category: "gov",
    tagline: "File monthly return, register employees, track IP, view challan.",
    description:
      "ESIC provides social security to workers earning ₹21,000/month or below. File the monthly return, register new employees as Insured Persons (IP), generate challans, and pull the IP coverage status. Reanzly flags employees crossing the wage ceiling for ESIC exit and surfaces the Form 37 (declaration of employment) workflow.",
    region: "IN",
    docsUrl: "https://www.esic.in/",
    mark: "ES",
    official: true,
    multiInstance: false,
    sandboxSupported: false,
    pricingSummary: "Free (govt portal)",
    entityIdLabel: "ESIC IP / Employer Code",
    requiresRegion: true,
    filingFrequencies: ["Monthly"],
    fields: [
      { id: "esicEmployerCode", label: "Employer Code", type: "text", required: true, placeholder: "12-digit code", helpText: "Allotted by the ESIC regional office." },
      { id: "esicUsername", label: "ESIC Portal Username", type: "text", required: true },
      { id: "esicPassword", label: "ESIC Password", type: "password", required: true, secret: true },
      { id: "state", label: "State / UT", type: "select", required: true, options: IN_STATES },
      { id: "subCode", label: "Sub-Code (optional)", type: "text", helpText: "Required if you file separately per branch." },
    ],
    capabilities: [
      { label: "Monthly return", supported: true },
      { label: "Employee registration (IP)", supported: true },
      { label: "Challan generation", supported: true },
      { label: "IP tracking", supported: true },
      { label: "Form 37 (employment declaration)", supported: true },
      { label: "Form 1 (declaration form)", supported: true },
      { label: "Exit on wage ceiling", supported: true },
      { label: "IP medical benefit status", supported: true },
      { label: "Pehchan card download", supported: true },
      { label: "Benefit claim tracking", supported: true },
    ],
    usedBy: ["payroll", "hr", "compliance", "employees"],
    syncConfig: {
      frequency: "daily",
      onDemand: true,
      typicalRecordsPerSync: 38,
      syncData: [
        { description: "Monthly return -> ESIC portal", direction: "push" },
        { description: "IP numbers + family details -> employee.esic_profile", direction: "pull" },
        { description: "Challan + receipt -> compliance.returns", direction: "pull" },
        { description: "Wage ceiling breaches -> exit queue", direction: "pull" },
      ],
    },
  },
  {
    id: "traces",
    name: "TRACES (TDS / Income Tax)",
    category: "gov",
    tagline: "File 24Q/26Q/27Q, generate Form 16/16A, view challan & defaults.",
    description:
      "TRACES is the TDS Reconciliation Analysis and Correction Enabling System by CBDT. File quarterly TDS returns - 24Q (salary), 26Q (non-salary), 27Q (non-resident) - and 27EQ (TCS). Auto-generate Form 16 (salary) and Form 16A (non-salary) for employees and vendors. Reconcile challans against the OLTAS (Online Tax Accounting System) pull and respond to default notices.",
    region: "IN",
    docsUrl: "https://www.tdscpc.gov.in/",
    mark: "TR",
    official: true,
    multiInstance: false,
    sandboxSupported: false,
    pricingSummary: "Free (govt portal)",
    entityIdLabel: "TAN",
    requiresRegion: true,
    filingFrequencies: ["Quarterly"],
    fields: [
      { id: "tan", label: "TAN", type: "text", required: true, placeholder: "MUMR12345B", helpText: "10-digit Tax Deduction Account Number." },
      { id: "tracesUserId", label: "TRACES User ID", type: "text", required: true },
      { id: "tracesPassword", label: "TRACES Password", type: "password", required: true, secret: true },
      { id: "deductorPan", label: "Deductor PAN", type: "text", required: true, placeholder: "ABCDE1234F" },
      { id: "state", label: "State / UT (TDS AO Circle)", type: "select", required: true, options: IN_STATES },
    ],
    capabilities: [
      { label: "24Q (salary TDS)", supported: true },
      { label: "26Q (non-salary TDS)", supported: true },
      { label: "27Q (non-resident TDS)", supported: true },
      { label: "27EQ (TCS)", supported: true },
      { label: "Form 16 (salary)", supported: true },
      { label: "Form 16A (non-salary)", supported: true },
      { label: "Challan status (OLTAS)", supported: true },
      { label: "Default notice response", supported: true },
      { label: "Justification report", supported: true },
      { label: "CPC benchmark correction", supported: true },
    ],
    usedBy: ["payroll", "ledger", "compliance", "vendors", "invoice"],
    syncConfig: {
      frequency: "daily",
      onDemand: true,
      typicalRecordsPerSync: 92,
      syncData: [
        { description: "Salary TDS -> 24Q return (quarterly push)", direction: "push" },
        { description: "Vendor TDS -> 26Q return (quarterly push)", direction: "push" },
        { description: "Form 16 PDF -> payroll.payslip_archive", direction: "pull" },
        { description: "Form 16A PDF -> vendor.tds_certificate", direction: "pull" },
        { description: "OLTAS challan match -> ledger.tds_paid", direction: "pull" },
        { description: "Default notice -> compliance.alerts", direction: "pull" },
      ],
    },
  },
  {
    id: "ptax",
    name: "Professional Tax (State Portal)",
    category: "gov",
    tagline: "State-wise PT filing - MH, KA, TN, DL, WB, GJ, RJ and more.",
    description:
      "Professional Tax is levied by state governments on salaried employees and professionals. Each state has its own portal, return cycle, and challan format. Reanzly consolidates every state into one connect point - file monthly returns, generate challans, enroll new employees, and amend your RC. Multi-instance lets you maintain separate connections per state for branches across India.",
    region: "IN",
    docsUrl: "https://www.mahagst.gov.in/",
    mark: "PT",
    official: true,
    multiInstance: true,
    sandboxSupported: false,
    pricingSummary: "Free (govt portal, state-wise)",
    entityIdLabel: "PT RC / TIN",
    requiresRegion: true,
    filingFrequencies: ["Monthly", "Annual"],
    fields: [
      { id: "state", label: "State / UT", type: "select", required: true, options: IN_STATES },
      { id: "ptRc", label: "PT RC / TIN Number", type: "text", required: true, placeholder: "2700012345" },
      { id: "ptUsername", label: "PT Portal Username", type: "text", required: true },
      { id: "ptPassword", label: "PT Portal Password", type: "password", required: true, secret: true },
      { id: "filingFrequency", label: "Filing Frequency", type: "select", required: true, options: [
        { value: "Monthly", label: "Monthly" },
        { value: "Annual", label: "Annual (where applicable)" },
      ] },
    ],
    capabilities: [
      { label: "Monthly return", supported: true },
      { label: "Annual return", supported: true },
      { label: "Challan generation", supported: true },
      { label: "Employee enrollment", supported: true },
      { label: "RC amendment", supported: true },
      { label: "Bulk employee upload", supported: true },
      { label: "Deductee master", supported: true },
      { label: "Refund claim", supported: true },
    ],
    usedBy: ["payroll", "hr", "compliance", "employees"],
    syncConfig: {
      frequency: "daily",
      onDemand: true,
      typicalRecordsPerSync: 45,
      syncData: [
        { description: "PT deduction per employee -> monthly return", direction: "push" },
        { description: "Challan + acknowledgment -> compliance.returns", direction: "pull" },
        { description: "RC validity + amendment status -> compliance.master", direction: "pull" },
      ],
    },
  },
  {
    id: "sarathi",
    name: "Sarathi (Driving Licences)",
    category: "gov",
    tagline: "Verify DL, add endorsements, track DL status and renewals.",
    description:
      "Sarathi is the central driving licence registry by MoRTH. Verify a driver's DL online, check badge validity (HMV/LMV/Transport), add endorsements (hazardous, tanker, multi-axle), and renew DLs approaching expiry. Reanzly runs nightly checks across the driver roster and raises alerts 60/30/7 days before expiry so renewals never lapse.",
    region: "IN",
    docsUrl: "https://parivahan.gov.in/sarathiservice/",
    mark: "SA",
    official: true,
    multiInstance: false,
    sandboxSupported: false,
    pricingSummary: "₹5/lookup",
    entityIdLabel: "DL Number",
    fields: [
      { id: "agentId", label: "Sarathi Agent ID", type: "text", required: true },
      { id: "apiToken", label: "API Token", type: "password", required: true, secret: true },
      { id: "rtoCode", label: "Primary RTO Code", type: "text", required: true, placeholder: "MH-14" },
    ],
    capabilities: [
      { label: "DL verification", supported: true },
      { label: "Badge / class check", supported: true },
      { label: "Endorsement add", supported: true },
      { label: "DL renewal", supported: true },
      { label: "LLR application", supported: true },
      { label: "Status tracking", supported: true },
      { label: "Conviction history", supported: true },
      { label: "Medical fitness flag", supported: true },
    ],
    usedBy: ["drivers-staff", "compliance", "hr"],
    syncConfig: {
      frequency: "daily",
      onDemand: true,
      typicalRecordsPerSync: 32,
      syncData: [
        { description: "DL status + badge validity -> driver.licence", direction: "pull" },
        { description: "Conviction history -> driver.compliance_alerts", direction: "pull" },
        { description: "DL expiry calendar -> compliance.expiry", direction: "pull" },
      ],
    },
  },
  {
    id: "fastag-nhai",
    name: "FASTag (NHAI / IHMCL)",
    category: "gov",
    tagline: "Vehicle FASTag status, recharge, statement, toll transactions.",
    description:
      "FASTag is the electronic toll collection system operated by IHMCL (a subsidiary of NHAI). Reanzly pulls live toll transactions per vehicle, reconciles them against trips by vehicle + date + toll plaza, and surfaces unmatched deductions. Track wallet balance, blacklist status, and recharge history across all your FASTag issuers (HDFC, ICICI, Axis, SBI, Kotak, Paytm) in one view.",
    region: "IN",
    docsUrl: "https://www.nhai.gov.in/",
    mark: "FT",
    official: true,
    multiInstance: true,
    sandboxSupported: false,
    pricingSummary: "₹0.30/transaction · free webhook",
    entityIdLabel: "FASTag ID / Wallet ID",
    fields: [
      { id: "issuer", label: "FASTag Issuer", type: "select", required: true, options: [
        { value: "hdfc", label: "HDFC Bank" },
        { value: "icici", label: "ICICI Bank" },
        { value: "axis", label: "Axis Bank" },
        { value: "sbi", label: "State Bank of India" },
        { value: "kotak", label: "Kotak Mahindra Bank" },
        { value: "paytm", label: "Paytm Payments Bank" },
        { value: "idbi", label: "IDBI Bank" },
        { value: "syndicate", label: "Canara Bank (Syndicate)" },
      ] },
      { id: "walletId", label: "Wallet ID / Cust ID", type: "text", required: true },
      { id: "apiToken", label: "Issuer API Token", type: "password", required: true, secret: true },
      { id: "webhookUrl", label: "Transaction Webhook", type: "webhook-url" },
    ],
    capabilities: [
      { label: "Vehicle FASTag status", supported: true },
      { label: "Wallet recharge", supported: true },
      { label: "Statement pull", supported: true },
      { label: "Toll transactions", supported: true },
      { label: "Low balance alert", supported: true },
      { label: "Blacklist check", supported: true },
      { label: "Trip auto-match", supported: true },
      { label: "Multi-vehicle", supported: true },
      { label: "Refund detection", supported: true },
      { label: "PAN-India plaza locator", supported: true },
    ],
    usedBy: ["trips", "expenses", "vehicles", "ledger"],
    syncConfig: {
      frequency: "real-time",
      onDemand: true,
      typicalRecordsPerSync: 412,
      syncData: [
        { description: "Real-time toll transactions -> expenses.toll", direction: "pull" },
        { description: "Wallet balance + blacklist -> vehicles.fastag_status", direction: "pull" },
        { description: "Daily statement -> ledger.toll_reconciliation", direction: "pull" },
        { description: "Unmatched tolls queue -> expenses.review", direction: "pull" },
      ],
    },
  },
  {
    id: "pucc",
    name: "PUCC (Pollution Under Control)",
    category: "gov",
    tagline: "PUC cert generation, expiry tracking, vehicle PUC verification.",
    description:
      "PUCC is the central Pollution Under Control certificate registry by MoRTH. Generate PUC certificates from certified testing centres, verify any vehicle's PUC status online, and track expiry across the entire fleet. Reanzly runs daily reconciliation and raises alerts 7 days before PUC expiry so vehicles never get fined at state border checks.",
    region: "IN",
    docsUrl: "https://vahan.parivahan.gov.in/pucc/",
    mark: "PU",
    official: true,
    multiInstance: false,
    sandboxSupported: false,
    pricingSummary: "₹60/cert · ₹5/verify",
    entityIdLabel: "PUC Centre ID",
    requiresRegion: true,
    fields: [
      { id: "centreId", label: "PUC Centre ID", type: "text", required: true },
      { id: "centrePassword", label: "Centre Password", type: "password", required: true, secret: true },
      { id: "state", label: "State / UT", type: "select", required: true, options: IN_STATES },
    ],
    capabilities: [
      { label: "PUC cert generation", supported: true },
      { label: "PUC verification", supported: true },
      { label: "Expiry tracking", supported: true },
      { label: "Bulk vehicle verify", supported: true },
      { label: "Test reading log", supported: true },
      { label: "Re-test scheduling", supported: true },
      { label: "Centre MIS reports", supported: true },
      { label: "Vehicle class mapping", supported: true },
    ],
    usedBy: ["vehicles", "compliance", "inspection"],
    syncConfig: {
      frequency: "daily",
      onDemand: true,
      typicalRecordsPerSync: 28,
      syncData: [
        { description: "PUC expiry dates -> vehicles.puc_expiry", direction: "pull" },
        { description: "7-day expiry alerts -> compliance.alerts", direction: "pull" },
        { description: "New certs generated -> vehicles.documents", direction: "pull" },
      ],
    },
  },
  {
    id: "national-permit",
    name: "National Permit (MoRTH)",
    category: "gov",
    tagline: "Apply / renew national permit, multi-state tax payment.",
    description:
      "National Permit authorises a goods vehicle to operate across all Indian states. Apply for a new permit, renew an existing one, and pay composite multi-state tax (currently ₹16,500/year for goods vehicles). Reanzly tracks permit validity per vehicle, surfaces renewal windows 30 days in advance, and stores authorisation letters for state-wise RTO produce-upon-demand.",
    region: "IN",
    docsUrl: "https://parivahan.gov.in/nationalpermit/",
    mark: "NP",
    official: true,
    multiInstance: false,
    sandboxSupported: false,
    pricingSummary: "₹16,500/year composite tax",
    entityIdLabel: "NLN / Permit Number",
    requiresRegion: true,
    fields: [
      { id: "state", label: "Home State / UT", type: "select", required: true, options: IN_STATES },
      { id: "agentId", label: "RTO Agent ID", type: "text", required: true },
      { id: "agentPassword", label: "RTO Agent Password", type: "password", required: true, secret: true },
      { id: "rtoCode", label: "Home RTO Code", type: "text", required: true, placeholder: "MH-14" },
    ],
    capabilities: [
      { label: "Apply new permit", supported: true },
      { label: "Renew permit", supported: true },
      { label: "Multi-state tax payment", supported: true },
      { label: "Permit status", supported: true },
      { label: "Authorisation letter", supported: true },
      { label: "Receipt download", supported: true },
      { label: "Bulk renewal", supported: true },
      { label: "Permit transfer", supported: false },
    ],
    usedBy: ["vehicles", "compliance", "trips"],
    syncConfig: {
      frequency: "on-demand",
      onDemand: true,
      typicalRecordsPerSync: 12,
      syncData: [
        { description: "Permit status + validity -> vehicles.permits", direction: "pull" },
        { description: "Authorisation letters -> vehicles.documents", direction: "pull" },
        { description: "Renewal calendar -> compliance.expiry", direction: "pull" },
      ],
    },
  },
  {
    id: "e-way-bill-gov",
    name: "e-Way Bill (NIC) - Govt Portal",
    category: "gov",
    tagline: "Generate, cancel, extend, verify e-Way Bills end-to-end.",
    description:
      "The NIC e-Way Bill portal is the authoritative source for GST e-Way Bills for movement of goods exceeding ₹50,000. Reanzly generates e-Way Bills directly from invoices (auto-filled Part-A + Part-B), cancels within 24h, extends validity before expiry, and verifies any e-Way Bill number by SMS or API. Bulk generation for an LR stack is one click.",
    region: "IN",
    docsUrl: "https://ewaybill.nic.in/",
    mark: "EW",
    official: true,
    multiInstance: true,
    sandboxSupported: true,
    pricingSummary: "Free (govt API)",
    entityIdLabel: "GSTIN",
    requiresRegion: true,
    filingFrequencies: ["Per consignment"],
    fields: [
      { id: "gstin", label: "GSTIN", type: "text", required: true, placeholder: "27ABCDE1234F1Z5" },
      { id: "ewbUsername", label: "e-Way Bill Username", type: "text", required: true },
      { id: "ewbPassword", label: "e-Way Bill Password", type: "password", required: true, secret: true },
      { id: "state", label: "State / UT", type: "select", required: true, options: IN_STATES },
      { id: "otpMode", label: "OTP / 2FA Mode", type: "select", options: [
        { value: "sms", label: "SMS OTP" },
        { value: "totp", label: "TOTP (auto)" },
      ] },
    ],
    capabilities: [
      { label: "Generate e-Way Bill", supported: true },
      { label: "Cancel (within 24h)", supported: true },
      { label: "Extend validity", supported: true },
      { label: "Verify by number", supported: true },
      { label: "Part-B update", supported: true },
      { label: "Transporter assignment", supported: true },
      { label: "Bulk generation", supported: true },
      { label: "SMS verification", supported: true },
      { label: "Auto from invoice", supported: true },
      { label: "Consolidated e-Way Bill", supported: true },
    ],
    usedBy: ["invoice", "lorry-receipts", "trips", "compliance"],
    syncConfig: {
      frequency: "real-time",
      onDemand: true,
      typicalRecordsPerSync: 86,
      syncData: [
        { description: "Invoice > ₹50k -> e-Way Bill Part-A + Part-B (real-time)", direction: "push" },
        { description: "e-Way Bill status + validity -> invoice.ewb_status", direction: "pull" },
        { description: "Expiry imminent (8h window) -> extend validity queue", direction: "push" },
        { description: "Cancel/extend events -> compliance.ewb_log", direction: "pull" },
      ],
    },
  },
  {
    id: "dgft",
    name: "DGFT (Foreign Trade)",
    category: "gov",
    tagline: "IEC verification, import/export licences, MEIS/SEIS, RoDTEP.",
    description:
      "DGFT is the Directorate General of Foreign Trade under the Ministry of Commerce. Verify your Importer Exporter Code (IEC), apply for and track import/export licences, monitor MEIS/SEIS incentive scrips, claim RoDTEP and RoSCTL benefits, and check EPCG (Export Promotion Capital Goods) authorisations. Reanzly reconciles your shipping bills against DGFT scrips to surface unclaimed incentives.",
    region: "IN",
    docsUrl: "https://www.dgft.gov.in/",
    mark: "DG",
    official: true,
    multiInstance: false,
    sandboxSupported: false,
    pricingSummary: "Free (govt portal)",
    entityIdLabel: "IEC",
    requiresRegion: true,
    fields: [
      { id: "iec", label: "IEC Code", type: "text", required: true, placeholder: "10-digit IEC" },
      { id: "dgftUserId", label: "DGFT User ID", type: "text", required: true },
      { id: "dgftPassword", label: "DGFT Password", type: "password", required: true, secret: true },
      { id: "state", label: "State / UT (DGFT Zonal Office)", type: "select", required: true, options: IN_STATES },
    ],
    capabilities: [
      { label: "IEC verification", supported: true },
      { label: "Import licence", supported: true },
      { label: "Export licence", supported: true },
      { label: "MEIS / SEIS status", supported: true },
      { label: "RoDTEP claim", supported: true },
      { label: "RoSCTL claim", supported: true },
      { label: "EPCG authorisation", supported: true },
      { label: "Advance authorisation", supported: true },
      { label: "Scrips ledger", supported: true },
      { label: "RCMC sync", supported: true },
    ],
    usedBy: ["compliance", "invoice", "ledger", "vendors"],
    syncConfig: {
      frequency: "daily",
      onDemand: true,
      typicalRecordsPerSync: 18,
      syncData: [
        { description: "IEC validity + address -> company.export_profile", direction: "pull" },
        { description: "MEIS/SEIS/RoDTEP scrips -> ledger.incentives", direction: "pull" },
        { description: "Licence status -> compliance.licences", direction: "pull" },
        { description: "Unclaimed incentives -> invoice.review_queue", direction: "pull" },
      ],
    },
  },
  {
    id: "mca",
    name: "MCA (Ministry of Corporate Affairs)",
    category: "gov",
    tagline: "Company master data, DIN, DSC verification, annual returns.",
    description:
      "MCA21 is the e-governance portal of the Ministry of Corporate Affairs. Pull your company's master data (CIN, incorporation date, directors, capital structure), verify Director Identification Numbers (DIN), confirm Digital Signature Certificate (DSC) validity, and file annual returns (MGT-7, AOC-4, DIR-3 KYC). Reanzly syncs this into the vendor and customer onboarding flow for KYC diligence.",
    region: "IN",
    docsUrl: "https://www.mca.gov.in/",
    mark: "MC",
    official: true,
    multiInstance: false,
    sandboxSupported: false,
    pricingSummary: "₹100/lookup · free DSC verify",
    entityIdLabel: "CIN / FCN",
    requiresRegion: true,
    fields: [
      { id: "cin", label: "CIN / FCN", type: "text", required: true, placeholder: "U60231MH2012PTC123456" },
      { id: "mcaUserId", label: "MCA User ID", type: "text", required: true },
      { id: "mcaPassword", label: "MCA Password", type: "password", required: true, secret: true },
      { id: "state", label: "State / UT (ROC)", type: "select", required: true, options: IN_STATES },
    ],
    capabilities: [
      { label: "Company master data", supported: true },
      { label: "DIN lookup", supported: true },
      { label: "DSC verification", supported: true },
      { label: "Annual return (MGT-7)", supported: true },
      { label: "AOC-4 (financials)", supported: true },
      { label: "DIR-3 KYC", supported: true },
      { label: "Charge details (CHG-1)", supported: true },
      { label: "Director history", supported: true },
      { label: "Vendor / customer KYC", supported: true },
      { label: "Strike-off status", supported: true },
    ],
    usedBy: ["vendors", "customers", "compliance", "superadmin-billing"],
    syncConfig: {
      frequency: "on-demand",
      onDemand: true,
      typicalRecordsPerSync: 6,
      syncData: [
        { description: "Company master + directors -> vendor/customer.kyc", direction: "pull" },
        { description: "DIN + DSC status -> compliance.signatories", direction: "pull" },
        { description: "Annual filing status -> compliance.calendar", direction: "pull" },
      ],
    },
  },
  {
    id: "india-post",
    name: "India Post (Bharat Net)",
    category: "gov",
    tagline: "Parcel tracking, speed post, business parcel booking, COD.",
    description:
      "India Post operates the largest postal network in the world. Pull parcel and speed-post tracking events, book business parcels for last-mile delivery to remote PIN codes, sync COD remittance cycles, and subscribe to tracking webhooks. Ideal for returns processing and reaching tier-3/4 PIN codes where private couriers don't deliver.",
    region: "IN",
    docsUrl: "https://www.indiapost.gov.in/",
    mark: "IP",
    official: true,
    multiInstance: false,
    sandboxSupported: true,
    pricingSummary: "₹0.50/track · parcel rates as per slab",
    fields: [
      { id: "customerId", label: "Business Customer ID", type: "text", required: true },
      { id: "apiToken", label: "API Token", type: "password", required: true, secret: true },
      { id: "webhookUrl", label: "Tracking Event Webhook", type: "webhook-url" },
    ],
    capabilities: [
      { label: "Parcel tracking", supported: true },
      { label: "Speed post tracking", supported: true },
      { label: "Business parcel booking", supported: true },
      { label: "COD remittance", supported: true },
      { label: "Tracking webhook", supported: true },
      { label: "Bulk booking", supported: true },
      { label: "PIN code serviceability", supported: true },
      { label: "Pickup request", supported: true },
    ],
    usedBy: ["trips", "ecommerce", "customers"],
    syncConfig: {
      frequency: "real-time",
      onDemand: true,
      typicalRecordsPerSync: 64,
      syncData: [
        { description: "Tracking events -> trips.milestones", direction: "pull" },
        { description: "COD remittance status -> ledger.cod", direction: "pull" },
        { description: "PIN code serviceability -> customers.serviceable", direction: "pull" },
      ],
    },
  },
];

/* ---------- Fuel Cards ---------- */
export const FUEL_PROVIDERS: IntegrationProvider[] = [
  {
    id: "indian-oil-fleet",
    name: "IndianOil Fleet Card",
    category: "fuel",
    tagline: "Fleet card for IOC pumps - controlled fuel purchases.",
    description:
      "IndianOil XTRAPOWER fleet card lets drivers refuel at any IOC pump. Reanzly pulls transaction data (litres, amount, odometer, pump location) and reconciles against vehicle trips.",
    region: "IN",
    docsUrl: "https://www.iocxtrapower.com/",
    mark: "IO",
    official: false,
    multiInstance: false,
    sandboxSupported: false,
    pricingSummary: "₹100/card/mo · 0.5% rebate",
    fields: [
      { id: "clientId", label: "Client ID", type: "text", required: true },
      { id: "clientSecret", label: "Client Secret", type: "password", required: true, secret: true },
      { id: "fleetId", label: "Fleet ID", type: "text", required: true },
    ],
    capabilities: [
      { label: "Transaction pull", supported: true },
      { label: "Card-vehicle mapping", supported: true },
      { label: "Pump locator", supported: true },
      { label: "Limit setting", supported: true },
      { label: "Rebate reconciliation", supported: true },
      { label: "PIN reset", supported: true },
      { label: "Card block", supported: true },
      { label: "BPCL/HPCL accept", supported: false },
    ],
    usedBy: ["fuel-energy", "vehicles", "expenses", "trips"],
  },
  {
    id: "hpcl-fleet",
    name: "HPCL Fleet Card",
    category: "fuel",
    tagline: "HP Pump fleet card with controlled diesel purchase.",
    description:
      "Hindustan Petroleum fleet card. Pull diesel transactions, set vehicle-level limits, and reconcile against odometer readings to detect pilferage.",
    region: "IN",
    docsUrl: "https://www.hpcl-fleet.com/",
    mark: "HP",
    official: false,
    multiInstance: false,
    sandboxSupported: false,
    pricingSummary: "₹100/card/mo · 0.4% rebate",
    fields: [
      { id: "apiToken", label: "API Token", type: "password", required: true, secret: true },
      { id: "fleetCode", label: "Fleet Code", type: "text", required: true },
    ],
    capabilities: [
      { label: "Transaction pull", supported: true },
      { label: "Card-vehicle mapping", supported: true },
      { label: "Pump locator", supported: true },
      { label: "Limit setting", supported: true },
      { label: "Rebate reconciliation", supported: true },
      { label: "PIN reset", supported: true },
      { label: "Card block", supported: true },
      { label: "IOC accept", supported: false },
    ],
    usedBy: ["fuel-energy", "vehicles", "expenses"],
  },
];

/* ---------- Banking ---------- */
export const BANKING_PROVIDERS: IntegrationProvider[] = [
  {
    id: "icici-corporate",
    name: "ICICI Corporate Banking API",
    category: "banking",
    tagline: "Corporate payouts, collections, and statement pulls.",
    description:
      "ICICI Bank Corporate Banking API. Push vendor payouts, pull bank statements, initiate NEFT/RTGS/IMPS, and reconcile customer payments automatically.",
    region: "IN",
    docsUrl: "https://www.icicibank.com/corporate/api-banking",
    mark: "IC",
    official: false,
    multiInstance: false,
    sandboxSupported: true,
    pricingSummary: "Custom enterprise pricing",
    fields: [
      { id: "apiUserId", label: "API User ID", type: "text", required: true },
      { id: "apiPassword", label: "API Password", type: "password", required: true, secret: true },
      { id: "corporateId", label: "Corporate ID", type: "text", required: true },
      { id: "accountId", label: "Account Number", type: "text", required: true },
      { id: "webhookUrl", label: "Payment Status Webhook", type: "webhook-url" },
    ],
    capabilities: [
      { label: "Statement pull", supported: true },
      { label: "NEFT/RTGS/IMPS payout", supported: true },
      { label: "UPI collection", supported: true },
      { label: "Cheque status", supported: true },
      { label: "Vendor payout batch", supported: true },
      { label: "Salary disbursement", supported: true },
      { label: "Auto-reconciliation", supported: true },
      { label: "Foreign outward remittance", supported: true },
    ],
    usedBy: ["payments", "expenses", "invoice", "payroll", "financial-ops"],
  },
  {
    id: "hdfc-corporate",
    name: "HDFC Corporate Banking API",
    category: "banking",
    tagline: "Corporate payouts, collections, and EVA banking.",
    description:
      "HDFC Bank Corporate API. Push payments, pull statements, validate IFSC, and reconcile customer collections. Best for fleets using HDFC as primary banker.",
    region: "IN",
    docsUrl: "https://www.hdfcbank.com/corporate/api-banking",
    mark: "HD",
    official: false,
    multiInstance: false,
    sandboxSupported: true,
    pricingSummary: "Custom enterprise pricing",
    fields: [
      { id: "clientId", label: "Client ID", type: "text", required: true },
      { id: "clientSecret", label: "Client Secret", type: "password", required: true, secret: true },
      { id: "corporateId", label: "Corporate ID", type: "text", required: true },
      { id: "accountId", label: "Account Number", type: "text", required: true },
    ],
    capabilities: [
      { label: "Statement pull", supported: true },
      { label: "NEFT/RTGS/IMPS payout", supported: true },
      { label: "UPI collection", supported: true },
      { label: "Cheque status", supported: true },
      { label: "Vendor payout batch", supported: true },
      { label: "Salary disbursement", supported: true },
      { label: "Auto-reconciliation", supported: true },
      { label: "Foreign outward", supported: false },
    ],
    usedBy: ["payments", "expenses", "invoice", "payroll", "financial-ops"],
  },
];

/* ---------- Email & Notifications ---------- */
export const EMAIL_PROVIDERS: IntegrationProvider[] = [
  {
    id: "sendgrid",
    name: "SendGrid",
    category: "extension",
    tagline: "Transactional email delivery with templates.",
    description:
      "SendGrid is a leading transactional email provider. Send invoice PDFs, POD confirmations, weekly reports, and onboarding emails with high deliverability.",
    region: "US",
    docsUrl: "https://docs.sendgrid.com/",
    mark: "SG",
    official: false,
    multiInstance: false,
    sandboxSupported: true,
    pricingSummary: "Free 100/day · ₹0.18/email",
    fields: [
      { id: "apiKey", label: "API Key", type: "password", placeholder: "SG.XXXXXXXX", required: true, secret: true },
      { id: "fromEmail", label: "From Email", type: "text", placeholder: "noreply@reanzly.com", required: true },
      { id: "fromName", label: "From Name", type: "text", placeholder: "Reanzly Logistics" },
    ],
    capabilities: [
      { label: "Transactional send", supported: true },
      { label: "Template engine", supported: true },
      { label: "Attachment PDF", supported: true },
      { label: "Bounce/complaint webhook", supported: true },
      { label: "Suppression list", supported: true },
      { label: "Sub-user (multi-tenant)", supported: true },
      { label: "Marketing campaigns", supported: true },
      { label: "SMS (via Twilio)", supported: false },
    ],
    usedBy: ["invoice", "pod", "documents", "automation"],
  },
  {
    id: "aws-ses",
    name: "AWS SES",
    category: "extension",
    tagline: "Amazon Simple Email Service - cheapest scale email.",
    description:
      "AWS SES is the cheapest transactional email at scale (₹0.08/email). Best for high-volume notifications. Pull bounce/complaint events via SNS.",
    region: "GLOBAL",
    docsUrl: "https://docs.aws.amazon.com/ses/",
    mark: "SE",
    official: false,
    multiInstance: false,
    sandboxSupported: true,
    pricingSummary: "₹0.08/email · free in EC2",
    fields: [
      { id: "accessKeyId", label: "AWS Access Key ID", type: "text", required: true },
      { id: "secretAccessKey", label: "AWS Secret Access Key", type: "password", required: true, secret: true },
      { id: "region", label: "Region", type: "select", options: [{ value: "ap-south-1", label: "Mumbai (ap-south-1)" }, { value: "ap-southeast-1", label: "Singapore" }, { value: "us-east-1", label: "N. Virginia" }] },
      { id: "fromEmail", label: "Verified From Email", type: "text", required: true },
    ],
    capabilities: [
      { label: "Transactional send", supported: true },
      { label: "Template engine", supported: true },
      { label: "Attachment PDF", supported: true },
      { label: "Bounce/complaint (SNS)", supported: true },
      { label: "Suppression list", supported: true },
      { label: "Dedicated IP", supported: true },
      { label: "Marketing", supported: false },
      { label: "Drag-drop editor", supported: false },
    ],
    usedBy: ["invoice", "pod", "documents", "automation"],
  },
];

/* ---------- CRM & Marketing ---------- */
export const CRM_PROVIDERS: IntegrationProvider[] = [
  {
    id: "hubspot",
    name: "HubSpot CRM",
    category: "extension",
    tagline: "Sync customers, deals, and engagement to HubSpot.",
    description:
      "HubSpot CRM integration. Sync customers as contacts, deals as opportunities, and engagement (calls, emails, meetings) back to HubSpot for marketing automation.",
    region: "US",
    docsUrl: "https://developers.hubspot.com/",
    mark: "HB",
    official: false,
    multiInstance: false,
    sandboxSupported: true,
    pricingSummary: "Free CRM · paid hubs from $20/mo",
    fields: [
      { id: "privateAppToken", label: "Private App Access Token", type: "password", placeholder: "pat-XXXX", required: true, secret: true },
      { id: "accountId", label: "Hub ID (Account ID)", type: "text", required: true },
    ],
    capabilities: [
      { label: "Contact sync", supported: true },
      { label: "Deal sync", supported: true },
      { label: "Company sync", supported: true },
      { label: "Engagement sync", supported: true },
      { label: "Custom objects", supported: true },
      { label: "Workflows trigger", supported: true },
      { label: "Lists", supported: true },
      { label: "Marketing emails", supported: true },
    ],
    usedBy: ["customers", "rate-cards", "automation"],
  },
  {
    id: "zoho-crm",
    name: "Zoho CRM",
    category: "extension",
    tagline: "Sync customers, leads, and deals to Zoho CRM.",
    description:
      "Zoho CRM integration. Sync customers as accounts, leads from IndiaMART/JustDial, and deals from rate-card negotiations. Push closed-won deals to invoice module.",
    region: "IN",
    docsUrl: "https://www.zoho.com/crm/developer/docs/api/",
    mark: "ZC",
    official: false,
    multiInstance: false,
    sandboxSupported: true,
    pricingSummary: "₹1,200/user/mo",
    fields: [
      { id: "accessToken", label: "OAuth Access Token", type: "password", required: true, secret: true },
      { id: "refreshToken", label: "Refresh Token", type: "password", required: true, secret: true },
      { id: "apiDomain", label: "API Domain", type: "text", placeholder: "https://www.zohoapis.in" },
    ],
    capabilities: [
      { label: "Lead sync", supported: true },
      { label: "Account sync", supported: true },
      { label: "Deal sync", supported: true },
      { label: "Contact sync", supported: true },
      { label: "Custom modules", supported: true },
      { label: "Workflow trigger", supported: true },
      { label: "Blueprints", supported: true },
      { label: "Marketing emails", supported: false },
    ],
    usedBy: ["customers", "rate-cards", "automation"],
  },
];

/* ---------- Insurance ---------- */
export const INSURANCE_PROVIDERS: IntegrationProvider[] = [
  {
    id: "digit-insurance",
    name: "Digit Insurance",
    category: "extension",
    tagline: "Quote, bind, and renew vehicle insurance policies.",
    description:
      "Digit Insurance API for vehicle insurance. Get instant quotes, issue new policies, and renew existing ones directly from the vehicle master.",
    region: "IN",
    docsUrl: "https://www.godigit.com/partners/api",
    mark: "DI",
    official: false,
    multiInstance: false,
    sandboxSupported: true,
    pricingSummary: "Per-policy commission",
    fields: [
      { id: "partnerCode", label: "Partner Code", type: "text", required: true },
      { id: "apiToken", label: "API Token", type: "password", required: true, secret: true },
      { id: "environment", label: "Environment", type: "select", required: true, options: [{ value: "production", label: "Production" }, { value: "uat", label: "UAT" }] },
    ],
    capabilities: [
      { label: "Quote (third-party)", supported: true },
      { label: "Quote (comprehensive)", supported: true },
      { label: "Policy issue", supported: true },
      { label: "Policy renewal", supported: true },
      { label: "Claim initiation", supported: true },
      { label: "Status check", supported: true },
      { label: "Cashless garage list", supported: true },
      { label: "Add-on covers", supported: true },
    ],
    usedBy: ["vehicles", "compliance", "documents"],
  },
  {
    id: "icici-lombard",
    name: "ICICI Lombard",
    category: "extension",
    tagline: "Vehicle insurance + transit/cargo cover via API.",
    description:
      "ICICI Lombard API for commercial vehicle insurance and marine cargo cover. Issue, renew, and claim - with transit insurance for shipments.",
    region: "IN",
    docsUrl: "https://www.icicilombard.com/partner-api",
    mark: "IL",
    official: false,
    multiInstance: false,
    sandboxSupported: true,
    pricingSummary: "Per-policy commission",
    fields: [
      { id: "partnerId", label: "Partner ID", type: "text", required: true },
      { id: "apiToken", label: "API Token", type: "password", required: true, secret: true },
    ],
    capabilities: [
      { label: "Vehicle quote", supported: true },
      { label: "Policy issue", supported: true },
      { label: "Renewal", supported: true },
      { label: "Marine cargo cover", supported: true },
      { label: "Transit insurance", supported: true },
      { label: "Claim filing", supported: true },
      { label: "Status check", supported: true },
      { label: "Cashless network", supported: true },
    ],
    usedBy: ["vehicles", "compliance", "trips", "documents"],
  },
];

/* ---------- Additional Payment / SMS / WhatsApp ---------- */
export const MORE_PAYMENT_PROVIDERS: IntegrationProvider[] = [
  {
    id: "pine-labs",
    name: "Pine Labs",
    category: "payment",
    tagline: "POS terminals + UPI QR + EMI at delivery point.",
    description:
      "Pine Labs enables in-person payments at delivery/cash-on-delivery points via POS terminals, UPI dynamic QR, and EMI options. Push payment links and reconcile instantly.",
    region: "IN",
    docsUrl: "https://www.pinelabs.com/developer",
    mark: "PL",
    official: false,
    multiInstance: true,
    sandboxSupported: true,
    pricingSummary: "1.5% per txn",
    fields: [
      { id: "accessCode", label: "Access Code", type: "text", required: true },
      { id: "secretKey", label: "Secret Key", type: "password", required: true, secret: true },
      { id: "merchantId", label: "Merchant ID", type: "text", required: true },
      { id: "webhookUrl", label: "Webhook URL", type: "webhook-url" },
    ],
    capabilities: [
      { label: "POS terminals", supported: true },
      { label: "UPI dynamic QR", supported: true },
      { label: "EMI at delivery", supported: true },
      { label: "Payment links", supported: true },
      { label: "Settlement reconciliation", supported: true },
      { label: "Refunds", supported: true },
      { label: "Cashless COD", supported: true },
      { label: "International cards", supported: false },
    ],
    usedBy: ["payments", "invoice", "trips"],
  },
  {
    id: "ccavenue",
    name: "CCAvenue",
    category: "payment",
    tagline: "Oldest Indian payment aggregator. Multi-currency.",
    description:
      "CCAvenue by Infibeam Avenues is one of the oldest Indian payment aggregators. Accept credit/debit cards, UPI, netbanking, wallets, EMI, and international multi-currency.",
    region: "IN",
    docsUrl: "https://www.ccavenue.com/api.jsp",
    mark: "CA",
    official: false,
    multiInstance: false,
    sandboxSupported: true,
    pricingSummary: "1.99% per txn",
    fields: [
      { id: "merchantId", label: "Merchant ID", type: "text", required: true },
      { id: "accessCode", label: "Access Code", type: "text", required: true },
      { id: "workingKey", label: "Working Key (encryption)", type: "password", required: true, secret: true },
      { id: "webhookUrl", label: "Webhook URL", type: "webhook-url" },
    ],
    capabilities: [
      { label: "Cards (domestic)", supported: true },
      { label: "UPI", supported: true },
      { label: "Netbanking (50+ banks)", supported: true },
      { label: "Wallets", supported: true },
      { label: "EMI", supported: true },
      { label: "Multi-currency", supported: true },
      { label: "Recurring mandates", supported: true },
      { label: "Refunds", supported: true },
    ],
    usedBy: ["payments", "invoice"],
  },
];

export const MORE_SMS_PROVIDERS: IntegrationProvider[] = [
  {
    id: "karix",
    name: "Karix (Tanla)",
    category: "sms",
    tagline: "Enterprise SMS + CPaaS + WhatsApp BSP.",
    description:
      "Karix (now Tanla) provides enterprise SMS, voice, and CPaaS. Strong DLT compliance and high throughput for transactional and OTP SMS.",
    region: "IN",
    docsUrl: "https://developers.karix.io/",
    mark: "KX",
    official: false,
    multiInstance: true,
    sandboxSupported: true,
    pricingSummary: "₹0.17/SMS",
    fields: [
      { id: "apiKey", label: "API Key", type: "password", required: true, secret: true },
      { id: "apiSecret", label: "API Secret", type: "password", required: true, secret: true },
      { id: "senderId", label: "Sender ID", type: "text", placeholder: "RENZLY", required: true },
      { id: "dltTemplateId", label: "DLT Template ID", type: "text" },
      { id: "dltPrincipalId", label: "DLT Principal Entity ID", type: "text" },
    ],
    capabilities: [
      { label: "Transactional SMS", supported: true },
      { label: "OTP SMS", supported: true },
      { label: "Promotional SMS", supported: true },
      { label: "DLT compliance", supported: true },
      { label: "Unicode (regional)", supported: true },
      { label: "Voice OTP", supported: true },
      { label: "WhatsApp BSP", supported: true },
      { label: "International SMS", supported: true },
    ],
    usedBy: ["automation", "trips", "pod", "invoice"],
  },
  {
    id: "solutions-infini",
    name: "Solutions Infini (Gupshup)",
    category: "sms",
    tagline: "Enterprise SMS aggregator (now part of Gupshup).",
    description:
      "Solutions Infini (acquired by Gupshup) is a popular Indian SMS aggregator. Best for high-volume transactional SMS at competitive rates.",
    region: "IN",
    docsUrl: "https://api.solutionsinfini.com/",
    mark: "SI",
    official: false,
    multiInstance: false,
    sandboxSupported: true,
    pricingSummary: "₹0.15/SMS",
    fields: [
      { id: "apiKey", label: "API Key", type: "password", required: true, secret: true },
      { id: "senderId", label: "Sender ID", type: "text", required: true },
      { id: "dltTemplateId", label: "DLT Template ID", type: "text" },
      { id: "dltPrincipalId", label: "DLT Principal Entity ID", type: "text" },
    ],
    capabilities: [
      { label: "Transactional SMS", supported: true },
      { label: "OTP SMS", supported: true },
      { label: "Promotional SMS", supported: true },
      { label: "DLT compliance", supported: true },
      { label: "Unicode", supported: true },
      { label: "Voice", supported: true },
      { label: "WhatsApp BSP", supported: true },
      { label: "International", supported: false },
    ],
    usedBy: ["automation", "trips", "pod"],
  },
];

/* ---------- Aggregate logistics providers ---------- */
export const ALL_LOGISTICS_PROVIDERS: IntegrationProvider[] = [
  ...FLEET_TELEMATICS_PROVIDERS,
  ...LOGISTICS_PLATFORM_PROVIDERS,
  ...ECOMMERCE_PROVIDERS,
  ...WAREHOUSE_PROVIDERS,
  ...MAPS_PROVIDERS,
  ...GOV_PROVIDERS,
  ...FUEL_PROVIDERS,
  ...BANKING_PROVIDERS,
  ...EMAIL_PROVIDERS,
  ...CRM_PROVIDERS,
  ...INSURANCE_PROVIDERS,
  ...MORE_PAYMENT_PROVIDERS,
  ...MORE_SMS_PROVIDERS,
];

/* New categories introduced by this file. */
export const NEW_CATEGORIES: {
  id: IntegrationCategory;
  meta: { label: string; description: string; multiInstance: boolean };
}[] = [
  {
    id: "logistics",
    meta: {
      label: "3PL & Shipping",
      description: "Aggregator and direct carrier APIs for parcel & LTL shipping.",
      multiInstance: true,
    },
  },
  {
    id: "ecommerce",
    meta: {
      label: "E-commerce Channels",
      description: "Pull orders and push fulfillments to e-commerce marketplaces.",
      multiInstance: true,
    },
  },
  {
    id: "warehouse",
    meta: {
      label: "Warehouse & WMS",
      description: "Inventory, pick-pack, and warehouse management systems.",
      multiInstance: true,
    },
  },
  {
    id: "maps",
    meta: {
      label: "Maps & Routing",
      description: "Geocoding, distance matrix, truck-aware routing.",
      multiInstance: false,
    },
  },
  {
    id: "gov",
    meta: {
      label: "Government & Compliance",
      description: "RC verification, customs filing, DigiLocker, GST.",
      multiInstance: false,
    },
  },
  {
    id: "fuel",
    meta: {
      label: "Fuel Cards",
      description: "Fleet cards for controlled fuel purchases at pumps.",
      multiInstance: true,
    },
  },
  {
    id: "banking",
    meta: {
      label: "Banking APIs",
      description: "Corporate banking for payouts, collections, reconciliation.",
      multiInstance: true,
    },
  },
];

/** Seed one realistic connection per new category so the marketplace isn't
 * an empty shell on first load. */
export interface LogisticsSeedConnection {
  providerId: string;
  status: "connected" | "sandbox" | "needs-config" | "error";
  mode: "live" | "test";
  priority?: number;
  isPrimary?: boolean;
  fieldValues: Record<string, string>;
  connectedAt: string;
  lastSyncAt?: string;
  lastSyncStatus?: "ok" | "error" | "pending";
  lastSyncMessage?: string;
}

export const LOGISTICS_SEED_CONNECTIONS: LogisticsSeedConnection[] = [
  {
    providerId: "google-maps",
    status: "connected",
    mode: "live",
    priority: 1,
    isPrimary: true,
    fieldValues: {
      apiKey: "AIzaSyREANZLY••••••••••••",
      projectId: "reanzly-prod",
    },
    connectedAt: new Date(Date.now() - 120 * 86400000).toISOString(),
    lastSyncAt: new Date(Date.now() - 90 * 1000).toISOString(),
    lastSyncStatus: "ok",
    lastSyncMessage: "1,42,318 API calls in last 24h",
  },
  {
    providerId: "indian-oil-fleet",
    status: "connected",
    mode: "live",
    priority: 1,
    isPrimary: true,
    fieldValues: {
      clientId: "REANZLY_TPT",
      clientSecret: "••••••••",
      fleetId: "FL-27481",
    },
    connectedAt: new Date(Date.now() - 78 * 86400000).toISOString(),
    lastSyncAt: new Date(Date.now() - 12 * 60000).toISOString(),
    lastSyncStatus: "ok",
    lastSyncMessage: "182 fuel transactions synced today · 8,412 L diesel",
  },
  {
    providerId: "motive",
    status: "connected",
    mode: "live",
    priority: 1,
    isPrimary: true,
    fieldValues: {
      apiKey: "live_REANZLY••••••",
      apiSecret: "••••••••",
      companyId: "29481",
    },
    connectedAt: new Date(Date.now() - 54 * 86400000).toISOString(),
    lastSyncAt: new Date(Date.now() - 38 * 1000).toISOString(),
    lastSyncStatus: "ok",
    lastSyncMessage: "47 vehicles streaming live · last ping 38s ago",
  },
  {
    providerId: "shiprocket",
    status: "sandbox",
    mode: "test",
    priority: 1,
    isPrimary: false,
    fieldValues: {
      email: "ops@reanzly.in",
      token: "••••••••",
    },
    connectedAt: new Date(Date.now() - 6 * 86400000).toISOString(),
    lastSyncAt: new Date(Date.now() - 2 * 3600000).toISOString(),
    lastSyncStatus: "ok",
    lastSyncMessage: "Sandbox - 4 test orders pushed today",
  },
  {
    providerId: "vahan",
    status: "connected",
    mode: "live",
    priority: 1,
    isPrimary: true,
    fieldValues: {
      apiToken: "••••••••",
      agencyCode: "AG-RENZLY-1142",
    },
    connectedAt: new Date(Date.now() - 41 * 86400000).toISOString(),
    lastSyncAt: new Date(Date.now() - 4 * 3600000).toISOString(),
    lastSyncStatus: "ok",
    lastSyncMessage: "32 RC verifications today · 1 expired fitness flagged",
  },
  {
    providerId: "gstn",
    status: "connected",
    mode: "live",
    priority: 1,
    isPrimary: true,
    fieldValues: {
      gstin: "27ABCDE1234F1Z5",
      gstUsername: "REANZLY_TPT",
      gstPassword: "••••••••",
      state: "MH",
      filingFrequency: "Monthly",
      otpMode: "totp",
    },
    connectedAt: new Date(Date.now() - 138 * 86400000).toISOString(),
    lastSyncAt: new Date(Date.now() - 47 * 60000).toISOString(),
    lastSyncStatus: "ok",
    lastSyncMessage: "184 GSTR-2A line items pulled · 12 ITC rows unmatched",
  },
  {
    providerId: "e-way-bill-gov",
    status: "connected",
    mode: "live",
    priority: 1,
    isPrimary: true,
    fieldValues: {
      gstin: "27ABCDE1234F1Z5",
      ewbUsername: "REANZLY_TPT",
      ewbPassword: "••••••••",
      state: "MH",
      otpMode: "totp",
    },
    connectedAt: new Date(Date.now() - 96 * 86400000).toISOString(),
    lastSyncAt: new Date(Date.now() - 90 * 1000).toISOString(),
    lastSyncStatus: "ok",
    lastSyncMessage: "86 e-Way Bills generated today · 3 nearing expiry",
  },
  {
    providerId: "epfo",
    status: "connected",
    mode: "live",
    priority: 1,
    isPrimary: true,
    fieldValues: {
      establishmentCode: "MHBAN0012345000",
      epfoUsername: "REANZLY_TPT",
      epfoPassword: "••••••••",
      state: "MH",
      uanSeed: "",
    },
    connectedAt: new Date(Date.now() - 74 * 86400000).toISOString(),
    lastSyncAt: new Date(Date.now() - 6 * 3600000).toISOString(),
    lastSyncStatus: "ok",
    lastSyncMessage: "ECR filed for 45 members · TRRN 0123456789 received",
  },
  {
    providerId: "fastag-nhai",
    status: "connected",
    mode: "live",
    priority: 1,
    isPrimary: true,
    fieldValues: {
      issuer: "hdfc",
      walletId: "FL-27481",
      apiToken: "••••••••",
    },
    connectedAt: new Date(Date.now() - 58 * 86400000).toISOString(),
    lastSyncAt: new Date(Date.now() - 38 * 1000).toISOString(),
    lastSyncStatus: "ok",
    lastSyncMessage: "412 toll transactions synced (last 1h) · 386 auto-matched",
  },
];
