"use client";

/* ============================================================
   SmartInsightsWidget
   ------------------------------------------------------------
   The flagship "AI" widget for the dashboard. Surfaces
   predictive insights generated by the in-browser insights
   engine (no LLM round-trip - instant + free).

   Features:
     - Hero strip with summary stats (critical count, at-risk
       amount, opportunity count)
     - Filter chips by category (All / Fleet / Finance /
       Operations / Compliance)
     - Insight cards with severity badge, rationale, evidence
       chips, confidence meter, and CTA button (navigates to
       the relevant module)
     - Dismissable (per-session) - dismissed insights stay
       hidden until reload
     - "Refresh" button re-runs the engine (no-op visually since
       the engine is deterministic, but it gives users a sense
       of control)

   Design:
     - Strict monochrome Swiss (foreground/muted/border only)
     - 6px radii, hairline borders, no shadows
     - Tabular mono for every number
     - Severity indicated by stroke weight + icon, never color
   ============================================================ */

import { useMemo, useState, type ReactElement } from "react";
import { cn } from "@/lib/utils";
import { useAppStore, type ModuleId } from "@/lib/store/app-store";
import { generateInsights, summarizeInsights, type Insight, type InsightCategory, type InsightSeverity } from "@/lib/insights/engine";
import { StatusBadge, LiveDot } from "@/components/shared/status-badge";
import { Btn } from "@/components/shared/btn";
import {
  Sparkles, AlertTriangle, TrendingUp, Brain, Zap, ArrowRight,
  RefreshCw, X, ShieldAlert, AlertCircle, Lightbulb, Activity,
} from "lucide-react";

const CATEGORY_FILTERS: { id: "all" | InsightCategory; label: string }[] = [
  { id: "all", label: "All" },
  { id: "fleet", label: "Fleet" },
  { id: "finance", label: "Finance" },
  { id: "operations", label: "Operations" },
  { id: "compliance", label: "Compliance" },
];

function severityVariant(s: InsightSeverity): "solid" | "outline" | "muted" {
  if (s === "critical" || s === "high") return "solid";
  if (s === "medium") return "outline";
  return "muted";
}

function kindIcon(k: Insight["kind"]) {
  if (k === "risk") return <AlertTriangle className="h-3.5 w-3.5" />;
  if (k === "opportunity") return <TrendingUp className="h-3.5 w-3.5" />;
  if (k === "anomaly") return <Activity className="h-3.5 w-3.5" />;
  return <Brain className="h-3.5 w-3.5" />;
}

function categoryLabel(c: InsightCategory): string {
  return c.charAt(0).toUpperCase() + c.slice(1);
}

export function SmartInsightsWidget(): ReactElement {
  const navigate = useAppStore((s) => s.navigate);
  const [filter, setFilter] = useState<"all" | InsightCategory>("all");
  const [dismissed, setDismissed] = useState<Set<string>>(new Set());
  const [refreshKey, setRefreshKey] = useState(0);

  // Generate insights (memoized - deterministic given the same input data,
  // so refreshKey forces a recompute even though the result is identical).
  const allInsights = useMemo(() => generateInsights(20), [refreshKey]);
  const visibleInsights = useMemo(
    () => allInsights.filter((i) => !dismissed.has(i.id) && (filter === "all" || i.category === filter)),
    [allInsights, dismissed, filter],
  );
  const summary = useMemo(() => summarizeInsights(allInsights), [allInsights]);

  function dismiss(id: string) {
    setDismissed((prev) => new Set(prev).add(id));
  }

  function handleAction(module: Insight["module"]) {
    navigate(module as ModuleId, "list");
  }

  return (
    <div className="flex h-full flex-col gap-3">
      {/* Header strip with summary */}
      <div className="flex items-center justify-between gap-2">
        <div className="flex items-center gap-2">
          <span className="flex h-6 w-6 items-center justify-center rounded-[4px] bg-foreground text-background">
            <Sparkles className="h-3.5 w-3.5" />
          </span>
          <span className="text-[13px] font-medium text-foreground">Smart Insights</span>
          <span className="flex items-center gap-1 text-[10px] font-medium uppercase tracking-wider text-muted-foreground">
            <LiveDot /> live
          </span>
        </div>
        <button
          onClick={() => setRefreshKey((k) => k + 1)}
          className="flex items-center gap-1 rounded-[4px] border border-border px-2 py-0.5 text-[10px] font-medium text-muted-foreground hover:bg-accent hover:text-foreground transition-colors tap"
          aria-label="Refresh insights"
        >
          <RefreshCw className="h-2.5 w-2.5" /> Refresh
        </button>
      </div>

      {/* Summary tiles */}
      <div className="grid grid-cols-4 gap-1.5">
        <SummaryTile
          icon={<ShieldAlert className="h-3 w-3" />}
          label="Critical"
          value={summary.bySeverity.critical}
          tone={summary.bySeverity.critical > 0 ? "solid" : "muted"}
        />
        <SummaryTile
          icon={<AlertCircle className="h-3 w-3" />}
          label="High"
          value={summary.bySeverity.high}
          tone={summary.bySeverity.high > 0 ? "outline" : "muted"}
        />
        <SummaryTile
          icon={<TrendingUp className="h-3 w-3" />}
          label="Opportunities"
          value={summary.byKind.opportunity}
          tone="muted"
        />
        <SummaryTile
          icon={<Zap className="h-3 w-3" />}
          label="At risk"
          value={summary.totalAtRiskINR > 0 ? `${(summary.totalAtRiskINR / 1000).toFixed(0)}k` : "0"}
          tone={summary.totalAtRiskINR > 0 ? "solid" : "muted"}
        />
      </div>

      {/* Category filter chips */}
      <div className="flex flex-wrap gap-1">
        {CATEGORY_FILTERS.map((c) => (
          <button
            key={c.id}
            onClick={() => setFilter(c.id)}
            className={cn(
              "rounded-[3px] border px-2 py-0.5 text-[10px] font-medium transition-colors tap",
              filter === c.id
                ? "border-foreground bg-foreground text-background"
                : "border-border text-muted-foreground hover:bg-accent hover:text-foreground",
            )}
          >
            {c.label}
          </button>
        ))}
      </div>

      {/* Insights list - scrollable */}
      <div className="scrollbar-thin -mr-1 flex-1 space-y-2 overflow-y-auto pr-1">
        {visibleInsights.length === 0 ? (
          <div className="flex flex-col items-center justify-center gap-2 py-8 text-center">
            <div className="flex h-9 w-9 items-center justify-center rounded-[6px] border border-border text-muted-foreground">
              <Lightbulb className="h-4 w-4" />
            </div>
            <p className="text-[12px] font-medium text-foreground">All clear</p>
            <p className="text-[11px] text-muted-foreground">
              No insights for this filter. The engine scans every module and surfaces risks, anomalies, and opportunities automatically.
            </p>
          </div>
        ) : (
          visibleInsights.slice(0, 8).map((insight) => (
            <InsightCard
              key={insight.id}
              insight={insight}
              onAction={() => handleAction(insight.module)}
              onDismiss={() => dismiss(insight.id)}
            />
          ))
        )}
      </div>
    </div>
  );
}

/* ============================================================
   Summary tile (monochrome, 4-up)
   ============================================================ */
function SummaryTile({
  icon, label, value, tone,
}: {
  icon: ReactElement;
  label: string;
  value: string | number;
  tone: "solid" | "outline" | "muted";
}) {
  return (
    <div
      className={cn(
        "flex flex-col gap-1 rounded-[5px] border px-2.5 py-2",
        tone === "solid" && "border-foreground/40 bg-foreground/5",
        tone === "outline" && "border-border bg-card",
        tone === "muted" && "border-border bg-muted/20",
      )}
    >
      <div className="flex items-center justify-between">
        <span className="text-[9px] font-medium uppercase tracking-wider text-muted-foreground">{label}</span>
        <span className="text-muted-foreground">{icon}</span>
      </div>
      <span className="text-[16px] font-medium leading-none tabular text-foreground">{value}</span>
    </div>
  );
}

/* ============================================================
   Insight card
   ============================================================ */
function InsightCard({
  insight, onAction, onDismiss,
}: {
  insight: Insight;
  onAction: () => void;
  onDismiss: () => void;
}) {
  const [expanded, setExpanded] = useState(false);
  return (
    <div
      className={cn(
        "group rounded-[5px] border bg-card p-2.5 transition-colors",
        insight.severity === "critical" || insight.severity === "high"
          ? "border-foreground/25 hover:border-foreground/40"
          : "border-border hover:border-foreground/30",
      )}
    >
      {/* Header row: kind icon + severity badge + dismiss */}
      <div className="flex items-start justify-between gap-2">
        <button
          onClick={() => setExpanded((e) => !e)}
          className="min-w-0 flex-1 text-left tap"
          aria-expanded={expanded}
        >
          <div className="flex items-center gap-1.5">
            <span className="text-muted-foreground">{kindIcon(insight.kind)}</span>
            <StatusBadge variant={severityVariant(insight.severity)} pulse={insight.severity === "critical"}>
              {insight.severity}
            </StatusBadge>
            <span className="text-[9px] uppercase tracking-wider text-muted-foreground">
              {categoryLabel(insight.category)}
            </span>
            <span className="text-[9px] tabular text-muted-foreground/70">
              · {Math.round(insight.confidence * 100)}%
            </span>
          </div>
          <div className="mt-1 text-[12px] font-medium leading-tight text-foreground">
            {insight.title}
          </div>
        </button>
        <button
          onClick={onDismiss}
          className="shrink-0 rounded-[3px] p-0.5 text-muted-foreground opacity-0 hover:bg-accent hover:text-foreground transition-opacity group-hover:opacity-100 tap"
          aria-label="Dismiss insight"
        >
          <X className="h-3 w-3" />
        </button>
      </div>

      {/* Rationale - always visible */}
      <p className="mt-1.5 text-[10.5px] leading-relaxed text-muted-foreground">
        {insight.rationale}
      </p>

      {/* Evidence chips - shown when expanded */}
      {expanded && insight.evidence.length > 0 && (
        <div className="mt-2 flex flex-wrap gap-1">
          {insight.evidence.map((e, i) => (
            <span
              key={i}
              className="rounded-[3px] border border-border bg-muted/30 px-1.5 py-0.5 text-[9.5px] tabular text-muted-foreground"
            >
              {e}
            </span>
          ))}
        </div>
      )}

      {/* Footer: impact + CTA */}
      <div className="mt-2 flex items-center justify-between gap-2">
        <span className="flex items-center gap-1 text-[10px] font-medium text-muted-foreground">
          <Zap className="h-2.5 w-2.5" />
          {insight.impact}
        </span>
        <Btn size="xs" variant="primary" iconRight={<ArrowRight className="h-2.5 w-2.5" />} onClick={onAction}>
          {insight.action}
        </Btn>
      </div>

      {/* Confidence meter (subtle, only for medium+ severity) */}
      {(insight.severity === "critical" || insight.severity === "high") && (
        <div className="mt-2 flex items-center gap-2">
          <span className="text-[9px] uppercase tracking-wider text-muted-foreground">Confidence</span>
          <div className="h-0.5 flex-1 overflow-hidden rounded-full bg-muted">
            <div
              className="h-full rounded-full bg-foreground"
              style={{ width: `${Math.round(insight.confidence * 100)}%` }}
            />
          </div>
          <span className="text-[9px] tabular text-muted-foreground">{Math.round(insight.confidence * 100)}%</span>
        </div>
      )}
    </div>
  );
}
